modLoader = "javafml"
loaderVersion = "[47,)"
license = "GNU GPL 3.0"
issueTrackerURL = "https://github.com/MysiuPysiu76/Bignay/issues"
logoFile = "icon.png"

[[mods]]
    modId = "bignay"
    version = "${mod_version}"
    displayName = "Bignay"
    authors = "MysiuPysiu"
    description = '''Small things, improving Minecraft bit by bit'''

[[dependencies.bignay]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.bignay]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"