modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
MixinConfigs = "bignay.mixins.json"

[[mods]]
    modId = "bignay"
    version = "1.1.1"
    displayName = "Bignay"
    authors = "Mysiu Pysiu"
    description = '''Small things, improving Minecraft bit by bit'''

[[dependencies.bignay]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.bignay]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"