package com.mysiupysiu.bignay.registry.init;

import com.mysiupysiu.bignay.registry.Registrar;
import com.mysiupysiu.bignay.registry.RegistrySupplier;
import com.mysiupysiu.bignay.utils.BignayWoodType;
import com.mysiupysiu.bignay.world.blocks.*;
import com.mysiupysiu.bignay.world.blocks.custom.*;
import com.mysiupysiu.bignay.world.items.BurnableBlockItem;
import com.mysiupysiu.bignay.world.items.EquipablePumpkinItem;
import com.mysiupysiu.bignay.world.items.ItemForBlock;
import com.mysiupysiu.bignay.world.worldgen.BignayConfiguredFeatures;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.WeatheringCopper;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.PushReaction;

import java.util.function.Supplier;

public class BignayBlocks {

    public static final Registrar<Block> BLOCKS = new Registrar<>();

    public static final RegistrySupplier<Block> WAX_BLOCK = block("wax_block", WaxBlock::new);
    public static final RegistrySupplier<Block> WITHER_BONE_BLOCK = block("wither_bone_block", WitherBoneBlock::new);
    public static final RegistrySupplier<Block> ARCHAEOLOGY_TABLE_BLOCK = block("archaeology_table", ArchaeologyTableBlock::new);
    public static final RegistrySupplier<Block> CHARCOAL_BLOCK = block("charcoal_block", () -> new BuildingBlock(Blocks.COAL_BLOCK));
    public static final RegistrySupplier<Block> COMPRESSED_STONE = block("compressed_stone", CompressedStone::new);
    public static final RegistrySupplier<Block> POT = block("pot", PotBlock::new);
    public static final RegistrySupplier<Block> GOLD_BARS = block("gold_bars", BarsBlock::new);
    public static final RegistrySupplier<Block> RANDOMIZER = block("randomizer", RandomizerBlock::new);

    public static final RegistrySupplier<Block> VERDANT_STEM = block("verdant_stem", () -> new NaturalNetherStemBlock(MapColor.COLOR_GREEN));
    public static final RegistrySupplier<Block> STRIPPED_VERDANT_STEM = block("stripped_verdant_stem", () -> new NetherStemBlock(MapColor.COLOR_GREEN));
    public static final RegistrySupplier<Block> STRIPPED_VERDANT_HYPHAE = block("stripped_verdant_hyphae", () -> new NetherStemBlock(MapColor.COLOR_GREEN));
    public static final RegistrySupplier<Block> VERDANT_HYPHAE = block("verdant_hyphae", () -> new NetherStemBlock(MapColor.COLOR_GREEN));
    public static final RegistrySupplier<Block> VERDANT_PLANKS = block("verdant_planks", VerdantPlanksBlock::new);
    public static final RegistrySupplier<Block> VERDANT_STAIRS = block("verdant_stairs", StairsBlock::new);
    public static final RegistrySupplier<Block> VERDANT_SLAB = block("verdant_slab", SlabsBlock::new);
    public static final RegistrySupplier<Block> VERDANT_FENCE = block("verdant_fence", () -> new WoodFenceBlock(Blocks.CRIMSON_FENCE_GATE));
    public static final RegistrySupplier<Block> VERDANT_FENCE_GATE = block("verdant_fence_gate", () -> new FenceGatesBlock(Blocks.WARPED_FENCE_GATE, BignayWoodType.VERDANT));
    public static final RegistrySupplier<Block> VERDANT_DOOR = block("verdant_door", () -> new DoorsBlock(Blocks.WARPED_TRAPDOOR, BignayWoodType.VERDANT.setType()));
    public static final RegistrySupplier<Block> VERDANT_TRAPDOOR = block("verdant_trapdoor", () -> new TrapDoorsBlock(Blocks.WARPED_TRAPDOOR, BignayWoodType.VERDANT.setType()));
    public static final RegistrySupplier<Block> VERDANT_PRESSURE_PLATE = block("verdant_pressure_plate", () -> new PressurePlatesBock(Blocks.WARPED_PRESSURE_PLATE, BignayWoodType.VERDANT.setType()));
    public static final RegistrySupplier<Block> VERDANT_BUTTON = block("verdant_button", () -> new WoodButtonBlock(Blocks.WARPED_BUTTON, BignayWoodType.VERDANT.setType()));
    public static final RegistrySupplier<Block> VERDANT_SIGN = blockOnly("verdant_sign", () -> new SignsBlock(Blocks.WARPED_SIGN, BignayWoodType.VERDANT));
    public static final RegistrySupplier<Block> VERDANT_WALL_SIGN = blockOnly("verdant_wall_sign", () -> new WallSignsBlock(Blocks.WARPED_WALL_SIGN, BignayWoodType.VERDANT));
    public static final RegistrySupplier<Block> VERDANT_HANGING_SIGN = blockOnly("verdant_hanging_sign", () -> new HangingSignsBlock(BlockBehaviour.Properties.copy(Blocks.WARPED_HANGING_SIGN), BignayWoodType.VERDANT));
    public static final RegistrySupplier<Block> VERDANT_WALL_HANGING_SIGN = blockOnly("verdant_wall_hanging_sign", () -> new WallHangingSignsBlock(BlockBehaviour.Properties.copy(Blocks.WARPED_WALL_HANGING_SIGN), BignayWoodType.VERDANT));

    public static final RegistrySupplier<Block> ACACIA_CAMPFIRE = block("acacia_campfire", CampfiresBlock::new);
    public static final RegistrySupplier<Block> BIRCH_CAMPFIRE = block("birch_campfire", CampfiresBlock::new);
    public static final RegistrySupplier<Block> CHERRY_CAMPFIRE = block("cherry_campfire", CampfiresBlock::new);
    public static final RegistrySupplier<Block> CRIMSON_CAMPFIRE = block("crimson_campfire", CampfiresBlock::new);
    public static final RegistrySupplier<Block> DARK_OAK_CAMPFIRE = block("dark_oak_campfire", CampfiresBlock::new);
    public static final RegistrySupplier<Block> JUNGLE_CAMPFIRE = block("jungle_campfire", CampfiresBlock::new);
    public static final RegistrySupplier<Block> MANGROVE_CAMPFIRE = block("mangrove_campfire", CampfiresBlock::new);
    public static final RegistrySupplier<Block> OAK_CAMPFIRE = block("oak_campfire", CampfiresBlock::new);
    public static final RegistrySupplier<Block> SPRUCE_CAMPFIRE = block("spruce_campfire", CampfiresBlock::new);
    public static final RegistrySupplier<Block> VERDANT_CAMPFIRE = block("verdant_campfire", CampfiresBlock::new);
    public static final RegistrySupplier<Block> WARPED_CAMPFIRE = block("warped_campfire", CampfiresBlock::new);

    public static final RegistrySupplier<Block> SOUL_ACACIA_CAMPFIRE = block("soul_acacia_campfire", CampfiresBlock.SoulCampfire::new);
    public static final RegistrySupplier<Block> SOUL_BIRCH_CAMPFIRE = block("soul_birch_campfire", CampfiresBlock.SoulCampfire::new);
    public static final RegistrySupplier<Block> SOUL_CHERRY_CAMPFIRE = block("soul_cherry_campfire", CampfiresBlock.SoulCampfire::new);
    public static final RegistrySupplier<Block> SOUL_CRIMSON_CAMPFIRE = block("soul_crimson_campfire", CampfiresBlock.SoulCampfire::new);
    public static final RegistrySupplier<Block> SOUL_DARK_OAK_CAMPFIRE = block("soul_dark_oak_campfire", CampfiresBlock.SoulCampfire::new);
    public static final RegistrySupplier<Block> SOUL_JUNGLE_CAMPFIRE = block("soul_jungle_campfire", CampfiresBlock.SoulCampfire::new);
    public static final RegistrySupplier<Block> SOUL_MANGROVE_CAMPFIRE = block("soul_mangrove_campfire", CampfiresBlock.SoulCampfire::new);
    public static final RegistrySupplier<Block> SOUL_OAK_CAMPFIRE = block("soul_oak_campfire", CampfiresBlock.SoulCampfire::new);
    public static final RegistrySupplier<Block> SOUL_SPRUCE_CAMPFIRE = block("soul_spruce_campfire", CampfiresBlock.SoulCampfire::new);
    public static final RegistrySupplier<Block> SOUL_VERDANT_CAMPFIRE = block("soul_verdant_campfire", CampfiresBlock.SoulCampfire::new);
    public static final RegistrySupplier<Block> SOUL_WARPED_CAMPFIRE = block("soul_warped_campfire", CampfiresBlock.SoulCampfire::new);

    public static final RegistrySupplier<Block> HOLLOW_ACACIA_LOG = block("hollow_acacia_log", () -> new HollowLogBlock(Blocks.ACACIA_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_BAMBOO_BLOCK = block("hollow_bamboo_block", () -> new HollowLogBlock(Blocks.BAMBOO_BLOCK), 150);
    public static final RegistrySupplier<Block> HOLLOW_BIRCH_LOG = block("hollow_birch_log", () -> new HollowLogBlock(Blocks.BIRCH_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_CHERRY_LOG = block("hollow_cherry_log", () -> new HollowLogBlock(Blocks.CHERRY_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_CRIMSON_STEM = block("hollow_crimson_stem", () -> new HollowLogBlock(Blocks.CRIMSON_STEM));
    public static final RegistrySupplier<Block> HOLLOW_DARK_OAK_LOG = block("hollow_dark_oak_log", () -> new HollowLogBlock(Blocks.DARK_OAK_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_JUNGLE_LOG = block("hollow_jungle_log", () -> new HollowLogBlock(Blocks.JUNGLE_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_MANGROVE_LOG = block("hollow_mangrove_log", () -> new HollowLogBlock(Blocks.MANGROVE_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_OAK_LOG = block("hollow_oak_log", () -> new HollowLogBlock(Blocks.OAK_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_SPRUCE_LOG = block("hollow_spruce_log", () -> new HollowLogBlock(Blocks.SPRUCE_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_VERDANT_STEM = block("hollow_verdant_stem", () -> new HollowLogBlock(VERDANT_STEM));
    public static final RegistrySupplier<Block> HOLLOW_WARPED_STEM = block("hollow_warped_stem", () -> new HollowLogBlock(Blocks.WARPED_STEM));

    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_ACACIA_LOG = block("hollow_stripped_acacia_log", () -> new HollowLogBlock(Blocks.STRIPPED_ACACIA_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_BAMBOO_BLOCK = block("hollow_stripped_bamboo_block", () -> new HollowLogBlock(Blocks.STRIPPED_BAMBOO_BLOCK), 150);
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_BIRCH_LOG = block("hollow_stripped_birch_log", () -> new HollowLogBlock(Blocks.STRIPPED_BIRCH_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_CHERRY_LOG = block("hollow_stripped_cherry_log", () -> new HollowLogBlock(Blocks.STRIPPED_CHERRY_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_CRIMSON_STEM = block("hollow_stripped_crimson_stem", () -> new HollowLogBlock(Blocks.STRIPPED_CRIMSON_STEM));
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_DARK_OAK_LOG = block("hollow_stripped_dark_oak_log", () -> new HollowLogBlock(Blocks.STRIPPED_DARK_OAK_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_JUNGLE_LOG = block("hollow_stripped_jungle_log", () -> new HollowLogBlock(Blocks.STRIPPED_JUNGLE_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_MANGROVE_LOG = block("hollow_stripped_mangrove_log", () -> new HollowLogBlock(Blocks.STRIPPED_MANGROVE_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_OAK_LOG = block("hollow_stripped_oak_log", () -> new HollowLogBlock(Blocks.STRIPPED_OAK_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_SPRUCE_LOG = block("hollow_stripped_spruce_log", () -> new HollowLogBlock(Blocks.STRIPPED_SPRUCE_LOG), 150);
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_VERDANT_STEM = block("hollow_stripped_verdant_stem", () -> new HollowLogBlock(VERDANT_STEM));
    public static final RegistrySupplier<Block> HOLLOW_STRIPPED_WARPED_STEM = block("hollow_stripped_warped_stem", () -> new HollowLogBlock(Blocks.STRIPPED_WARPED_STEM));

    public static final RegistrySupplier<Block> CRACKED_STONE_BRICK_STAIRS = block("cracked_stone_brick_stairs", () -> new StairsBlock(Blocks.CRACKED_STONE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_DEEPSLATE_BRICK_STAIRS = block("cracked_deepslate_brick_stairs", () -> new StairsBlock(Blocks.DEEPSLATE_BRICK_STAIRS));
    public static final RegistrySupplier<Block> CRACKED_DEEPSLATE_TILE_STAIRS = block("cracked_deepslate_tile_stairs", () -> new StairsBlock(Blocks.DEEPSLATE_TILES));
    public static final RegistrySupplier<Block> CRACKED_POLISHED_BLACKSTONE_STAIRS = block("cracked_polished_blackstone_brick_stairs", () -> new StairsBlock(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_NETHER_BRICK_STAIRS = block("cracked_nether_brick_stairs", () -> new StairsBlock(Blocks.CRACKED_NETHER_BRICKS));
    public static final RegistrySupplier<Block> SMOOTH_STONE_STAIRS = block("smooth_stone_stairs", () -> new StairsBlock(Blocks.SMOOTH_STONE));

    public static final RegistrySupplier<Block> CRACKED_STONE_BRICK_SLAB = block("cracked_stone_brick_slab", () -> new SlabsBlock(Blocks.CRACKED_STONE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_DEEPSLATE_BRICK_SLAB = block("cracked_deepslate_brick_slab", () -> new SlabsBlock(Blocks.DEEPSLATE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_DEEPSLATE_TILE_SLAB = block("cracked_deepslate_tile_slab", () -> new SlabsBlock(Blocks.DEEPSLATE_TILES));
    public static final RegistrySupplier<Block> CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB = block("cracked_polished_blackstone_brick_slab", () -> new SlabsBlock(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_NETHER_BRICK_SLAB = block("cracked_nether_brick_slab", () -> new SlabsBlock(Blocks.CRACKED_STONE_BRICKS));

    public static final RegistrySupplier<Block> CRACKED_STONE_BRICK_WALL = block("cracked_stone_brick_wall", () -> new WallsBlock(Blocks.CRACKED_STONE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_DEEPSLATE_BRICK_WALL = block("cracked_deepslate_brick_wall", () -> new WallsBlock(Blocks.DEEPSLATE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_DEEPSLATE_TILE_WALL = block("cracked_deepslate_tile_wall", () -> new WallsBlock(Blocks.DEEPSLATE_TILES));
    public static final RegistrySupplier<Block> CRACKED_POLISHED_BLACKSTONE_BRICK_WALL = block("cracked_polished_blackstone_brick_wall", () -> new WallsBlock(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_NETHER_BRICK_WALL = block("cracked_nether_brick_wall", () -> new WallsBlock(Blocks.CRACKED_NETHER_BRICKS));
    public static final RegistrySupplier<Block> STONE_WALL = block("stone_wall", () -> new WallsBlock(Blocks.STONE));

    public static final RegistrySupplier<Block> VERTICAL_ACACIA_PLANKS = block("vertical_acacia_planks", () -> new DecorativeWoodBlock(Blocks.ACACIA_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_BAMBOO_PLANKS = block("vertical_bamboo_planks", () -> new DecorativeWoodBlock(Blocks.BAMBOO_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_BIRCH_PLANKS = block("vertical_birch_planks", () -> new DecorativeWoodBlock(Blocks.BIRCH_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_CHERRY_PLANKS = block("vertical_cherry_planks", () -> new DecorativeWoodBlock(Blocks.CHERRY_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_CRIMSON_PLANKS = block("vertical_crimson_planks", () -> new DecorativeWoodBlock(Blocks.CRIMSON_PLANKS));
    public static final RegistrySupplier<Block> VERTICAL_DARK_OAK_PLANKS = block("vertical_dark_oak_planks", () -> new DecorativeWoodBlock(Blocks.DARK_OAK_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_JUNGLE_PLANKS = block("vertical_jungle_planks", () -> new DecorativeWoodBlock(Blocks.JUNGLE_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_MANGROVE_PLANKS = block("vertical_mangrove_planks", () -> new DecorativeWoodBlock(Blocks.MANGROVE_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_OAK_PLANKS = block("vertical_oak_planks", () -> new DecorativeWoodBlock(Blocks.OAK_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_SPRUCE_PLANKS = block("vertical_spruce_planks", () -> new DecorativeWoodBlock(Blocks.SPRUCE_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_VERDANT_PLANKS = block("vertical_verdant_planks", () -> new DecorativeWoodBlock(VERDANT_PLANKS.get()));
    public static final RegistrySupplier<Block> VERTICAL_WARPED_PLANKS = block("vertical_warped_planks", () -> new DecorativeWoodBlock(Blocks.WARPED_PLANKS));

    public static final RegistrySupplier<Block> VERTICAL_ACACIA_PLANK_STAIRS = block("vertical_acacia_plank_stairs", () -> new StairsBlock(Blocks.ACACIA_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_BAMBOO_PLANK_STAIRS = block("vertical_bamboo_plank_stairs", () -> new StairsBlock(Blocks.BAMBOO_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_BIRCH_PLANK_STAIRS = block("vertical_birch_plank_stairs", () -> new StairsBlock(Blocks.BIRCH_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_CHERRY_PLANK_STAIRS = block("vertical_cherry_plank_stairs", () -> new StairsBlock(Blocks.CHERRY_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_CRIMSON_PLANK_STAIRS = block("vertical_crimson_plank_stairs", () -> new StairsBlock(Blocks.CRIMSON_PLANKS));
    public static final RegistrySupplier<Block> VERTICAL_DARK_OAK_PLANK_STAIRS = block("vertical_dark_oak_plank_stairs", () -> new StairsBlock(Blocks.DARK_OAK_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_JUNGLE_PLANK_STAIRS = block("vertical_jungle_plank_stairs", () -> new StairsBlock(Blocks.JUNGLE_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_MANGROVE_PLANK_STAIRS = block("vertical_mangrove_plank_stairs", () -> new StairsBlock(Blocks.MANGROVE_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_OAK_PLANK_STAIRS = block("vertical_oak_plank_stairs", () -> new StairsBlock(Blocks.OAK_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_SPRUCE_PLANK_STAIRS = block("vertical_spruce_plank_stairs", () -> new StairsBlock(Blocks.SPRUCE_PLANKS), 300);
    public static final RegistrySupplier<Block> VERTICAL_VERDANT_PLANK_STAIRS = block("vertical_verdant_plank_stairs", () -> new StairsBlock(VERDANT_PLANKS));
    public static final RegistrySupplier<Block> VERTICAL_WARPED_PLANK_STAIRS = block("vertical_warped_plank_stairs", () -> new StairsBlock(Blocks.WARPED_PLANKS));

    public static final RegistrySupplier<Block> VERTICAL_ACACIA_PLANK_SLAB = block("vertical_acacia_plank_slab", () -> new SlabsBlock(Blocks.ACACIA_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_BAMBOO_PLANK_SLAB = block("vertical_bamboo_plank_slab", () -> new SlabsBlock(Blocks.BAMBOO_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_BIRCH_PLANK_SLAB = block("vertical_birch_plank_slab", () -> new SlabsBlock(Blocks.BIRCH_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_CHERRY_PLANK_SLAB = block("vertical_cherry_plank_slab", () -> new SlabsBlock(Blocks.CHERRY_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_CRIMSON_PLANK_SLAB = block("vertical_crimson_plank_slab", () -> new SlabsBlock(Blocks.CRIMSON_PLANKS));
    public static final RegistrySupplier<Block> VERTICAL_DARK_OAK_PLANK_SLAB = block("vertical_dark_oak_plank_slab", () -> new SlabsBlock(Blocks.DARK_OAK_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_JUNGLE_PLANK_SLAB = block("vertical_jungle_plank_slab", () -> new SlabsBlock(Blocks.JUNGLE_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_MANGROVE_PLANK_SLAB = block("vertical_mangrove_plank_slab", () -> new SlabsBlock(Blocks.MANGROVE_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_OAK_PLANK_SLAB = block("vertical_oak_plank_slab", () -> new SlabsBlock(Blocks.OAK_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_SPRUCE_PLANK_SLAB = block("vertical_spruce_plank_slab", () -> new SlabsBlock(Blocks.SPRUCE_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_VERDANT_PLANK_SLAB = block("vertical_verdant_plank_slab", () -> new SlabsBlock(VERDANT_PLANKS));
    public static final RegistrySupplier<Block> VERTICAL_WARPED_PLANK_SLAB = block("vertical_warped_plank_slab", () -> new SlabsBlock(Blocks.WARPED_PLANKS));

    public static final RegistrySupplier<Block> VERDANT_NYLIUM = block("verdant_nylium", () -> new NetherNyliumBlock(MapColor.COLOR_GREEN));
    public static final RegistrySupplier<Block> VERDANT_FUNGUS = block("verdant_fungus", () -> new NetherFungusBlock(BignayConfiguredFeatures.VERDANT_FUNGUS, VERDANT_NYLIUM.get()));
    public static final RegistrySupplier<Block> VERDANT_ROOTS = block("verdant_roots", () -> new NetherRootsBlock(MapColor.COLOR_GREEN));
    public static final RegistrySupplier<Block> VERDANT_WART_BLOCK = block("verdant_wart_block", () -> new NetherWartBlock(MapColor.COLOR_GREEN));
    public static final RegistrySupplier<Block> POTTED_VERDANT_FUNGUS = blockOnly("potted_verdant_fungus", () -> new FlowerPotsBlock(VERDANT_FUNGUS));
    public static final RegistrySupplier<Block> POTTED_VERDANT_ROOTS = blockOnly("potted_verdant_roots", () -> new FlowerPotsBlock(VERDANT_ROOTS));
    public static final RegistrySupplier<Block> VERDANT_SPROUTS = block("verdant_sprouts", () -> new SproutsBlock(MapColor.COLOR_GREEN));
    public static final RegistrySupplier<Block> CRIMSON_SPROUTS = block("crimson_sprouts", () -> new SproutsBlock(MapColor.CRIMSON_NYLIUM));

    public static final RegistrySupplier<Block> PALE_PUMPKIN = block("pale_pumpkin", () -> new PalePumpkinBlock(MapColor.COLOR_LIGHT_GRAY));
    public static final RegistrySupplier<Block> CARVED_PALE_PUMPKIN = equipablePumpkin("carved_pale_pumpkin", EquipablePumpkinBlock.PalePumpkin::new);
    public static final RegistrySupplier<Block> PALE_PUMPKIN_STEM = blockOnly("pale_pumpkin_stem", () -> new PumpkinStemBlock(PALE_PUMPKIN::get, BignayItems.PALE_PUMPKIN_SEEDS::get, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).noCollission().randomTicks().instabreak().sound(SoundType.HARD_CROP).pushReaction(PushReaction.DESTROY)));
    public static final RegistrySupplier<Block> ATTACHED_PALE_PUMPKIN_STEM = blockOnly("attached_pale_pumpkin_stem", () -> new AttachedPumpkinStemBlock(PALE_PUMPKIN::get, BignayItems.PALE_PUMPKIN_SEEDS::get, BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).noCollission().instabreak().sound(SoundType.HARD_CROP).pushReaction(PushReaction.DESTROY)));
    public static final RegistrySupplier<Block> PALE_JACK_O_LANTERN = block("pale_jack_o_lantern", JackOLantern.Pale::new);
    public static final RegistrySupplier<Block> SOUL_JACK_O_LANTERN = block("soul_jack_o_lantern", JackOLantern.Soul::new);
    public static final RegistrySupplier<Block> SOUL_PALE_JACK_O_LANTERN = block("soul_pale_jack_o_lantern", JackOLantern.SoulPale::new);

    public static final RegistrySupplier<Block> HAPPY_CARVED_PUMPKIN = equipablePumpkin("happy_carved_pumpkin", EquipablePumpkinBlock::new);
    public static final RegistrySupplier<Block> HAPPY_CARVED_PALE_PUMPKIN = equipablePumpkin("happy_carved_pale_pumpkin", EquipablePumpkinBlock.PalePumpkin::new);
    public static final RegistrySupplier<Block> HAPPY_JACK_O_LANTERN = block("happy_jack_o_lantern", JackOLantern::new);
    public static final RegistrySupplier<Block> HAPPY_PALE_JACK_O_LANTERN = block("happy_pale_jack_o_lantern", JackOLantern.Pale::new);
    public static final RegistrySupplier<Block> HAPPY_SOUL_JACK_O_LANTERN = block("happy_soul_jack_o_lantern", JackOLantern.Soul::new);
    public static final RegistrySupplier<Block> HAPPY_SOUL_PALE_JACK_O_LANTERN = block("happy_soul_pale_jack_o_lantern", JackOLantern.SoulPale::new);
    public static final RegistrySupplier<Block> ANXIOUS_CARVED_PUMPKIN = equipablePumpkin("anxious_carved_pumpkin", EquipablePumpkinBlock::new);
    public static final RegistrySupplier<Block> ANXIOUS_CARVED_PALE_PUMPKIN = equipablePumpkin("anxious_carved_pale_pumpkin", EquipablePumpkinBlock.PalePumpkin::new);
    public static final RegistrySupplier<Block> ANXIOUS_JACK_O_LANTERN = block("anxious_jack_o_lantern", JackOLantern::new);
    public static final RegistrySupplier<Block> ANXIOUS_PALE_JACK_O_LANTERN = block("anxious_pale_jack_o_lantern", JackOLantern.Pale::new);
    public static final RegistrySupplier<Block> ANXIOUS_SOUL_JACK_O_LANTERN = block("anxious_soul_jack_o_lantern", JackOLantern.Soul::new);
    public static final RegistrySupplier<Block> ANXIOUS_SOUL_PALE_JACK_O_LANTERN = block("anxious_soul_pale_jack_o_lantern", JackOLantern.SoulPale::new);
    public static final RegistrySupplier<Block> SKULL_CARVED_PUMPKIN = equipablePumpkin("skull_carved_pumpkin", EquipablePumpkinBlock::new);
    public static final RegistrySupplier<Block> SKULL_CARVED_PALE_PUMPKIN = equipablePumpkin("skull_carved_pale_pumpkin", EquipablePumpkinBlock.PalePumpkin::new);
    public static final RegistrySupplier<Block> SKULL_JACK_O_LANTERN = block("skull_jack_o_lantern", JackOLantern::new);
    public static final RegistrySupplier<Block> SKULL_PALE_JACK_O_LANTERN = block("skull_pale_jack_o_lantern", JackOLantern.Pale::new);
    public static final RegistrySupplier<Block> SKULL_SOUL_JACK_O_LANTERN = block("skull_soul_jack_o_lantern", JackOLantern.Soul::new);
    public static final RegistrySupplier<Block> SKULL_SOUL_PALE_JACK_O_LANTERN = block("skull_soul_pale_jack_o_lantern", JackOLantern.SoulPale::new);
    public static final RegistrySupplier<Block> DERPY_CARVED_PUMPKIN = equipablePumpkin("derpy_carved_pumpkin", EquipablePumpkinBlock::new);
    public static final RegistrySupplier<Block> DERPY_CARVED_PALE_PUMPKIN = equipablePumpkin("derpy_carved_pale_pumpkin", EquipablePumpkinBlock.PalePumpkin::new);
    public static final RegistrySupplier<Block> DERPY_JACK_O_LANTERN = block("derpy_jack_o_lantern", JackOLantern::new);
    public static final RegistrySupplier<Block> DERPY_PALE_JACK_O_LANTERN = block("derpy_pale_jack_o_lantern", JackOLantern.Pale::new);
    public static final RegistrySupplier<Block> DERPY_SOUL_JACK_O_LANTERN = block("derpy_soul_jack_o_lantern", JackOLantern.Soul::new);
    public static final RegistrySupplier<Block> DERPY_SOUL_PALE_JACK_O_LANTERN = block("derpy_soul_pale_jack_o_lantern", JackOLantern.SoulPale::new);
    public static final RegistrySupplier<Block> ANGRY_CARVED_PUMPKIN = equipablePumpkin("angry_carved_pumpkin", EquipablePumpkinBlock::new);
    public static final RegistrySupplier<Block> ANGRY_CARVED_PALE_PUMPKIN = equipablePumpkin("angry_carved_pale_pumpkin", EquipablePumpkinBlock.PalePumpkin::new);
    public static final RegistrySupplier<Block> ANGRY_JACK_O_LANTERN = block("angry_jack_o_lantern", JackOLantern::new);
    public static final RegistrySupplier<Block> ANGRY_PALE_JACK_O_LANTERN = block("angry_pale_jack_o_lantern", JackOLantern.Pale::new);
    public static final RegistrySupplier<Block> ANGRY_SOUL_JACK_O_LANTERN = block("angry_soul_jack_o_lantern", JackOLantern.Soul::new);
    public static final RegistrySupplier<Block> ANGRY_SOUL_PALE_JACK_O_LANTERN = block("angry_soul_pale_jack_o_lantern", JackOLantern.SoulPale::new);

    public static final RegistrySupplier<Block> BASALT_BRICKS = block("basalt_bricks", () -> new BuildingBlock(Blocks.BASALT));
    public static final RegistrySupplier<Block> BASALT_BRICK_SLAB = block("basalt_brick_slab", () -> new SlabsBlock(BASALT_BRICKS));
    public static final RegistrySupplier<Block> BASALT_BRICK_STAIRS = block("basalt_brick_stairs", () -> new StairsBlock(BASALT_BRICKS));
    public static final RegistrySupplier<Block> BASALT_BRICK_VERTICAL_SLAB = block("basalt_brick_vertical_slab", () -> new VerticalSlabBlock(BASALT_BRICKS));
    public static final RegistrySupplier<Block> BASALT_BRICK_WALL = block("basalt_brick_wall", () -> new WallsBlock(BASALT_BRICKS));
    public static final RegistrySupplier<Block> CHISELED_BASALT = block("chiseled_basalt", () -> new BuildingBlock(Blocks.BASALT));
    public static final RegistrySupplier<Block> BASALT_PILLAR = block("basalt_pillar", () -> new PillarBlock(BASALT_BRICKS));
    public static final RegistrySupplier<Block> SMOOTH_BASALT_STAIRS = block("smooth_basalt_stairs", () -> new StairsBlock(BASALT_BRICKS.get()));
    public static final RegistrySupplier<Block> SMOOTH_BASALT_SLAB = block("smooth_basalt_slab", () -> new SlabsBlock(BASALT_BRICKS.get()));
    public static final RegistrySupplier<Block> SMOOTH_BASALT_VERTICAL_SLAB = block("smooth_basalt_vertical_slab", () -> new VerticalSlabBlock(BASALT_BRICKS.get()));
    public static final RegistrySupplier<Block> COBBLED_BASALT = block("cobbled_basalt", () -> new PillarBlock(Blocks.BASALT));
    public static final RegistrySupplier<Block> CRACKED_BASALT_BRICKS = block("cracked_basalt_bricks", () -> new BuildingBlock(Blocks.BASALT));
    public static final RegistrySupplier<Block> CRACKED_BASALT_BRICK_SLAB = block("cracked_basalt_brick_slab", () -> new SlabsBlock(CRACKED_BASALT_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_BASALT_BRICK_STAIRS = block("cracked_basalt_brick_stairs", () -> new StairsBlock(CRACKED_BASALT_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_BASALT_BRICK_WALL = block("cracked_basalt_brick_wall", () -> new WallsBlock(CRACKED_BASALT_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_BASALT_BRICK_VERTICAL_SLAB = block("cracked_basalt_brick_vertical_slab", () -> new VerticalSlabBlock(CRACKED_BASALT_BRICKS));
    public static final RegistrySupplier<Block> BASALTIC_LAVA = block("basaltic_lava", BasalticLavaBlock::new);

    public static final RegistrySupplier<Block> IRON_HEAVY_CHAIN = block("iron_heavy_chain", HeavyChainBlock::new);
    public static final RegistrySupplier<Block> GOLDEN_CHAIN = block("golden_chain", ChainsBlock::new);
    public static final RegistrySupplier<Block> GOLDEN_HEAVY_CHAIN = block("golden_heavy_chain", HeavyChainBlock::new);

    public static final RegistrySupplier<Block> ACACIA_BOOKSHELF = block("acacia_bookshelf", BookshelfBlock::new, 300);
    public static final RegistrySupplier<Block> BAMBOO_BOOKSHELF = block("bamboo_bookshelf", BookshelfBlock::new, 300);
    public static final RegistrySupplier<Block> BIRCH_BOOKSHELF = block("birch_bookshelf", BookshelfBlock::new, 300);
    public static final RegistrySupplier<Block> CHERRY_BOOKSHELF = block("cherry_bookshelf", BookshelfBlock::new, 300);
    public static final RegistrySupplier<Block> CRIMSON_BOOKSHELF = block("crimson_bookshelf", BookshelfBlock::new);
    public static final RegistrySupplier<Block> DARK_OAK_BOOKSHELF = block("dark_oak_bookshelf", BookshelfBlock::new, 300);
    public static final RegistrySupplier<Block> JUNGLE_BOOKSHELF = block("jungle_bookshelf", BookshelfBlock::new, 300);
    public static final RegistrySupplier<Block> MANGROVE_BOOKSHELF = block("mangrove_bookshelf", BookshelfBlock::new, 300);
    public static final RegistrySupplier<Block> OAK_BOOKSHELF = block("oak_bookshelf", BookshelfBlock::new, 300);
    public static final RegistrySupplier<Block> SPRUCE_BOOKSHELF = block("spruce_bookshelf", BookshelfBlock::new, 300);
    public static final RegistrySupplier<Block> VERDANT_BOOKSHELF = block("verdant_bookshelf", BookshelfBlock::new);
    public static final RegistrySupplier<Block> WARPED_BOOKSHELF = block("warped_bookshelf", BookshelfBlock::new);

    public static final RegistrySupplier<Block> BLUE_NETHER_BRICKS = block("blue_nether_bricks", () -> new BuildingBlock(Blocks.RED_NETHER_BRICKS));
    public static final RegistrySupplier<Block> BLUE_NETHER_BRICK_SLAB = block("blue_nether_brick_slab", () -> new SlabsBlock(BLUE_NETHER_BRICKS));
    public static final RegistrySupplier<Block> BLUE_NETHER_BRICK_STAIRS = block("blue_nether_brick_stairs", () -> new StairsBlock(BLUE_NETHER_BRICKS));
    public static final RegistrySupplier<Block> BLUE_NETHER_BRICK_WALL = block("blue_nether_brick_wall", () -> new WallsBlock(BLUE_NETHER_BRICKS));
    public static final RegistrySupplier<Block> BLUE_NETHER_BRICK_VERTICAL_SLAB = block("blue_nether_brick_vertical_slab", () -> new VerticalSlabBlock(BLUE_NETHER_BRICKS));
    public static final RegistrySupplier<Block> GREEN_NETHER_BRICKS = block("green_nether_bricks", () -> new BuildingBlock(Blocks.RED_NETHER_BRICKS));
    public static final RegistrySupplier<Block> GREEN_NETHER_BRICK_SLAB = block("green_nether_brick_slab", () -> new SlabsBlock(GREEN_NETHER_BRICKS));
    public static final RegistrySupplier<Block> GREEN_NETHER_BRICK_STAIRS = block("green_nether_brick_stairs", () -> new StairsBlock(GREEN_NETHER_BRICKS));
    public static final RegistrySupplier<Block> GREEN_NETHER_BRICK_WALL = block("green_nether_brick_wall", () -> new WallsBlock(GREEN_NETHER_BRICKS));
    public static final RegistrySupplier<Block> GREEN_NETHER_BRICK_VERTICAL_SLAB = block("green_nether_brick_vertical_slab", () -> new VerticalSlabBlock(GREEN_NETHER_BRICKS));

    public static final RegistrySupplier<Block> MOSSY_STONE = block("mossy_stone", () -> new BuildingBlock(Blocks.STONE));
    public static final RegistrySupplier<Block> MOSSY_STONE_SLAB = block("mossy_stone_slab", () -> new SlabsBlock(MOSSY_STONE));
    public static final RegistrySupplier<Block> MOSSY_STONE_STAIRS = block("mossy_stone_stairs", () -> new StairsBlock(MOSSY_STONE));
    public static final RegistrySupplier<Block> MOSSY_STONE_WALL = block("mossy_stone_wall", () -> new WallsBlock(MOSSY_STONE));
    public static final RegistrySupplier<Block> MOSSY_STONE_VERTICAL_SLAB = block("mossy_stone_vertical_slab", () -> new VerticalSlabBlock(MOSSY_STONE));
    public static final RegistrySupplier<Block> MOSSY_CRACKED_STONE_BRICKS = block("mossy_cracked_stone_bricks", () -> new BuildingBlock(Blocks.MOSSY_STONE_BRICKS));
    public static final RegistrySupplier<Block> MOSSY_CRACKED_STONE_BRICK_SLAB = block("mossy_cracked_stone_brick_slab", () -> new SlabsBlock(MOSSY_CRACKED_STONE_BRICKS));
    public static final RegistrySupplier<Block> MOSSY_CRACKED_STONE_BRICK_STAIRS = block("mossy_cracked_stone_brick_stairs", () -> new StairsBlock(MOSSY_CRACKED_STONE_BRICKS));
    public static final RegistrySupplier<Block> MOSSY_CRACKED_STONE_BRICK_WALL = block("mossy_cracked_stone_brick_wall", () -> new WallsBlock(MOSSY_CRACKED_STONE_BRICKS));
    public static final RegistrySupplier<Block> MOSSY_CRACKED_STONE_BRICK_VERTICAL_SLAB = block("mossy_cracked_stone_brick_vertical_slab", () -> new VerticalSlabBlock(MOSSY_CRACKED_STONE_BRICKS));
    public static final RegistrySupplier<Block> MOSSY_CHISELED_STONE_BRICKS = block("mossy_chiseled_stone_bricks", () -> new BuildingBlock(Blocks.MOSSY_STONE_BRICKS));

    public static final RegistrySupplier<Block> ACACIA_WOOD_FENCE = block("acacia_wood_fence", () -> new WoodFenceBlock(Blocks.ACACIA_FENCE), 300);
    public static final RegistrySupplier<Block> BAMBOO_BLOCK_FENCE = block("bamboo_block_fence", () -> new WoodFenceBlock(Blocks.BAMBOO_FENCE), 300);
    public static final RegistrySupplier<Block> BIRCH_WOOD_FENCE = block("birch_wood_fence", () -> new WoodFenceBlock(Blocks.BIRCH_FENCE), 300);
    public static final RegistrySupplier<Block> CHERRY_WOOD_FENCE = block("cherry_wood_fence", () -> new WoodFenceBlock(Blocks.CHERRY_FENCE), 300);
    public static final RegistrySupplier<Block> CRIMSON_HYPHAE_FENCE = block("crimson_hyphae_fence", () -> new WoodFenceBlock(Blocks.CRIMSON_FENCE));
    public static final RegistrySupplier<Block> DARK_OAK_WOOD_FENCE = block("dark_oak_wood_fence", () -> new WoodFenceBlock(Blocks.DARK_OAK_FENCE), 300);
    public static final RegistrySupplier<Block> JUNGLE_WOOD_FENCE = block("jungle_wood_fence", () -> new WoodFenceBlock(Blocks.JUNGLE_FENCE), 300);
    public static final RegistrySupplier<Block> MANGROVE_WOOD_FENCE = block("mangrove_wood_fence", () -> new WoodFenceBlock(Blocks.MANGROVE_FENCE), 300);
    public static final RegistrySupplier<Block> OAK_WOOD_FENCE = block("oak_wood_fence", () -> new WoodFenceBlock(Blocks.OAK_FENCE), 300);
    public static final RegistrySupplier<Block> SPRUCE_WOOD_FENCE = block("spruce_wood_fence", () -> new WoodFenceBlock(Blocks.SPRUCE_FENCE), 300);
    public static final RegistrySupplier<Block> VERDANT_HYPHAE_FENCE = block("verdant_hyphae_fence", () -> new WoodFenceBlock(VERDANT_FENCE));
    public static final RegistrySupplier<Block> WARPED_HYPHAE_FENCE = block("warped_hyphae_fence", () -> new WoodFenceBlock(Blocks.WARPED_FENCE));

    public static final RegistrySupplier<Block> STRIPPED_ACACIA_WOOD_FENCE = block("stripped_acacia_wood_fence", () -> new WoodFenceBlock(Blocks.ACACIA_FENCE), 300);
    public static final RegistrySupplier<Block> STRIPPED_BIRCH_WOOD_FENCE = block("stripped_birch_wood_fence", () -> new WoodFenceBlock(Blocks.BIRCH_FENCE), 300);
    public static final RegistrySupplier<Block> STRIPPED_CHERRY_WOOD_FENCE = block("stripped_cherry_wood_fence", () -> new WoodFenceBlock(Blocks.CHERRY_FENCE), 300);
    public static final RegistrySupplier<Block> STRIPPED_CRIMSON_HYPHAE_FENCE = block("stripped_crimson_hyphae_fence", () -> new WoodFenceBlock(Blocks.CRIMSON_FENCE));
    public static final RegistrySupplier<Block> STRIPPED_DARK_OAK_WOOD_FENCE = block("stripped_dark_oak_wood_fence", () -> new WoodFenceBlock(Blocks.DARK_OAK_FENCE), 300);
    public static final RegistrySupplier<Block> STRIPPED_JUNGLE_WOOD_FENCE = block("stripped_jungle_wood_fence", () -> new WoodFenceBlock(Blocks.JUNGLE_FENCE), 300);
    public static final RegistrySupplier<Block> STRIPPED_MANGROVE_WOOD_FENCE = block("stripped_mangrove_wood_fence", () -> new WoodFenceBlock(Blocks.MANGROVE_FENCE), 300);
    public static final RegistrySupplier<Block> STRIPPED_OAK_WOOD_FENCE = block("stripped_oak_wood_fence", () -> new WoodFenceBlock(Blocks.OAK_FENCE), 300);
    public static final RegistrySupplier<Block> STRIPPED_SPRUCE_WOOD_FENCE = block("stripped_spruce_wood_fence", () -> new WoodFenceBlock(Blocks.SPRUCE_FENCE), 300);
    public static final RegistrySupplier<Block> STRIPPED_VERDANT_HYPHAE_FENCE = block("stripped_verdant_hyphae_fence", () -> new WoodFenceBlock(VERDANT_FENCE));
    public static final RegistrySupplier<Block> STRIPPED_WARPED_HYPHAE_FENCE = block("stripped_warped_hyphae_fence", () -> new WoodFenceBlock(Blocks.WARPED_FENCE));

    public static final RegistrySupplier<Block> ENDERMAN_HEAD = blockOnly("enderman_head", () -> new HeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_HEAD)));
    public static final RegistrySupplier<Block> ENDERMAN_WALL_HEAD = blockOnly("enderman_wall_head", () -> new WallHeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_WALL_HEAD)));
    public static final RegistrySupplier<Block> SPIDER_HEAD = blockOnly("spider_head", () -> new HeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_HEAD)));
    public static final RegistrySupplier<Block> SPIDER_WALL_HEAD = blockOnly("spider_wall_head", () -> new WallHeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_WALL_HEAD)));
    public static final RegistrySupplier<Block> BLAZE_HEAD = blockOnly("blaze_head", () -> new HeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_HEAD)));
    public static final RegistrySupplier<Block> BLAZE_WALL_HEAD = blockOnly("blaze_wall_head", () -> new WallHeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_WALL_HEAD)));
    public static final RegistrySupplier<Block> HUSK_HEAD = blockOnly("husk_head", () -> new HeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_HEAD)));
    public static final RegistrySupplier<Block> HUSK_WALL_HEAD = blockOnly("husk_wall_head", () -> new WallHeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_WALL_HEAD)));
    public static final RegistrySupplier<Block> SLIME_HEAD = blockOnly("slime_head", () -> new HeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_HEAD)));
    public static final RegistrySupplier<Block> SLIME_WALL_HEAD = blockOnly("slime_wall_head", () -> new WallHeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_WALL_HEAD)));
    public static final RegistrySupplier<Block> CAVE_SPIDER_HEAD = blockOnly("cave_spider_head", () -> new HeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_HEAD)));
    public static final RegistrySupplier<Block> CAVE_SPIDER_WALL_HEAD = blockOnly("cave_spider_wall_head", () -> new WallHeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_WALL_HEAD)));
    public static final RegistrySupplier<Block> MAGMA_CUBE_HEAD = blockOnly("magma_cube_head", () -> new HeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_HEAD)));
    public static final RegistrySupplier<Block> MAGMA_CUBE_WALL_HEAD = blockOnly("magma_cube_wall_head", () -> new WallHeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_WALL_HEAD)));
    public static final RegistrySupplier<Block> DROWNED_HEAD = blockOnly("drowned_head", () -> new HeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_HEAD)));
    public static final RegistrySupplier<Block> DROWNED_WALL_HEAD = blockOnly("drowned_wall_head", () -> new WallHeadBlock(BlockBehaviour.Properties.copy(Blocks.CREEPER_WALL_HEAD)));
    public static final RegistrySupplier<Block> STRAY_SKULL = blockOnly("stray_skull", () -> new HeadBlock(BlockBehaviour.Properties.copy(Blocks.SKELETON_SKULL)));
    public static final RegistrySupplier<Block> STRAY_WALL_SKULL = blockOnly("stray_wall_skull", () -> new WallHeadBlock(BlockBehaviour.Properties.copy(Blocks.SKELETON_WALL_SKULL)));

    public static final RegistrySupplier<Block> ACACIA_MOSAIC = block("acacia_mosaic", () -> new DecorativeWoodBlock(Blocks.ACACIA_PLANKS), 300);
    public static final RegistrySupplier<Block> BIRCH_MOSAIC = block("birch_mosaic", () -> new DecorativeWoodBlock(Blocks.BIRCH_PLANKS), 300);
    public static final RegistrySupplier<Block> CHERRY_MOSAIC = block("cherry_mosaic", () -> new DecorativeWoodBlock(Blocks.CHERRY_PLANKS), 300);
    public static final RegistrySupplier<Block> CRIMSON_MOSAIC = block("crimson_mosaic", () -> new DecorativeWoodBlock(Blocks.CRIMSON_PLANKS));
    public static final RegistrySupplier<Block> DARK_OAK_MOSAIC = block("dark_oak_mosaic", () -> new DecorativeWoodBlock(Blocks.DARK_OAK_PLANKS), 300);
    public static final RegistrySupplier<Block> JUNGLE_MOSAIC = block("jungle_mosaic", () -> new DecorativeWoodBlock(Blocks.JUNGLE_PLANKS), 300);
    public static final RegistrySupplier<Block> MANGROVE_MOSAIC = block("mangrove_mosaic", () -> new DecorativeWoodBlock(Blocks.MANGROVE_PLANKS), 300);
    public static final RegistrySupplier<Block> OAK_MOSAIC = block("oak_mosaic", () -> new DecorativeWoodBlock(Blocks.OAK_PLANKS), 300);
    public static final RegistrySupplier<Block> SPRUCE_MOSAIC = block("spruce_mosaic", () -> new DecorativeWoodBlock(Blocks.SPRUCE_PLANKS), 300);
    public static final RegistrySupplier<Block> VERDANT_MOSAIC = block("verdant_mosaic", () -> new DecorativeWoodBlock(BignayBlocks.VERDANT_PLANKS));
    public static final RegistrySupplier<Block> WARPED_MOSAIC = block("warped_mosaic", () -> new DecorativeWoodBlock(Blocks.WARPED_PLANKS));

    public static final RegistrySupplier<Block> ACACIA_MOSAIC_STAIRS = block("acacia_mosaic_stairs", () -> new StairsBlock(ACACIA_MOSAIC), 300);
    public static final RegistrySupplier<Block> BIRCH_MOSAIC_STAIRS = block("birch_mosaic_stairs", () -> new StairsBlock(BIRCH_MOSAIC), 300);
    public static final RegistrySupplier<Block> CHERRY_MOSAIC_STAIRS = block("cherry_mosaic_stairs", () -> new StairsBlock(CHERRY_MOSAIC), 300);
    public static final RegistrySupplier<Block> CRIMSON_MOSAIC_STAIRS = block("crimson_mosaic_stairs", () -> new StairsBlock(CRIMSON_MOSAIC));
    public static final RegistrySupplier<Block> DARK_OAK_MOSAIC_STAIRS = block("dark_oak_mosaic_stairs", () -> new StairsBlock(DARK_OAK_MOSAIC), 300);
    public static final RegistrySupplier<Block> JUNGLE_MOSAIC_STAIRS = block("jungle_mosaic_stairs", () -> new StairsBlock(JUNGLE_MOSAIC), 300);
    public static final RegistrySupplier<Block> MANGROVE_MOSAIC_STAIRS = block("mangrove_mosaic_stairs", () -> new StairsBlock(MANGROVE_MOSAIC), 300);
    public static final RegistrySupplier<Block> OAK_MOSAIC_STAIRS = block("oak_mosaic_stairs", () -> new StairsBlock(OAK_MOSAIC), 300);
    public static final RegistrySupplier<Block> SPRUCE_MOSAIC_STAIRS = block("spruce_mosaic_stairs", () -> new StairsBlock(SPRUCE_MOSAIC), 300);
    public static final RegistrySupplier<Block> VERDANT_MOSAIC_STAIRS = block("verdant_mosaic_stairs", () -> new StairsBlock(VERDANT_MOSAIC));
    public static final RegistrySupplier<Block> WARPED_MOSAIC_STAIRS = block("warped_mosaic_stairs", () -> new StairsBlock(WARPED_MOSAIC));

    public static final RegistrySupplier<Block> ACACIA_MOSAIC_SLAB = block("acacia_mosaic_slab", () -> new SlabsBlock(ACACIA_MOSAIC), 150);
    public static final RegistrySupplier<Block> BIRCH_MOSAIC_SLAB = block("birch_mosaic_slab", () -> new SlabsBlock(BIRCH_MOSAIC), 150);
    public static final RegistrySupplier<Block> CHERRY_MOSAIC_SLAB = block("cherry_mosaic_slab", () -> new SlabsBlock(CHERRY_MOSAIC), 150);
    public static final RegistrySupplier<Block> CRIMSON_MOSAIC_SLAB = block("crimson_mosaic_slab", () -> new SlabsBlock(CRIMSON_MOSAIC));
    public static final RegistrySupplier<Block> DARK_OAK_MOSAIC_SLAB = block("dark_oak_mosaic_slab", () -> new SlabsBlock(DARK_OAK_MOSAIC), 150);
    public static final RegistrySupplier<Block> JUNGLE_MOSAIC_SLAB = block("jungle_mosaic_slab", () -> new SlabsBlock(JUNGLE_MOSAIC), 150);
    public static final RegistrySupplier<Block> MANGROVE_MOSAIC_SLAB = block("mangrove_mosaic_slab", () -> new SlabsBlock(MANGROVE_MOSAIC), 150);
    public static final RegistrySupplier<Block> OAK_MOSAIC_SLAB = block("oak_mosaic_slab", () -> new SlabsBlock(OAK_MOSAIC), 150);
    public static final RegistrySupplier<Block> SPRUCE_MOSAIC_SLAB = block("spruce_mosaic_slab", () -> new SlabsBlock(SPRUCE_MOSAIC), 150);
    public static final RegistrySupplier<Block> VERDANT_MOSAIC_SLAB = block("verdant_mosaic_slab", () -> new SlabsBlock(VERDANT_MOSAIC));
    public static final RegistrySupplier<Block> WARPED_MOSAIC_SLAB = block("warped_mosaic_slab", () -> new SlabsBlock(WARPED_MOSAIC));

    public static final RegistrySupplier<Block> POLISHED_ANDESITE_WALL = block("polished_andesite_wall", () -> new WallsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> SMOOTH_ANDESITE = block("smooth_andesite", () -> new BuildingBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> SMOOTH_ANDESITE_SLAB = block("smooth_andesite_slab", () -> new SlabsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> SMOOTH_ANDESITE_STAIRS = block("smooth_andesite_stairs", () -> new StairsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> SMOOTH_ANDESITE_WALL = block("smooth_andesite_wall", () -> new WallsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> SMOOTH_ANDESITE_VERTICAL_SLAB = block("smooth_andesite_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> ANDESITE_BRICKS = block("andesite_bricks", () -> new BuildingBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> ANDESITE_BRICK_SLAB = block("andesite_brick_slab", () -> new SlabsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> ANDESITE_BRICK_STAIRS = block("andesite_brick_stairs", () -> new StairsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> ANDESITE_BRICK_WALL = block("andesite_brick_wall", () -> new WallsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> ANDESITE_BRICK_VERTICAL_SLAB = block("andesite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> CRACKED_ANDESITE_BRICKS = block("cracked_andesite_bricks", () -> new BuildingBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> CRACKED_ANDESITE_BRICK_SLAB = block("cracked_andesite_brick_slab", () -> new SlabsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> CRACKED_ANDESITE_BRICK_STAIRS = block("cracked_andesite_brick_stairs", () -> new StairsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> CRACKED_ANDESITE_BRICK_WALL = block("cracked_andesite_brick_wall", () -> new WallsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> CRACKED_ANDESITE_BRICK_VERTICAL_SLAB = block("cracked_andesite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> MOSSY_ANDESITE_BRICKS = block("mossy_andesite_bricks", () -> new BuildingBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> MOSSY_ANDESITE_BRICK_SLAB = block("mossy_andesite_brick_slab", () -> new SlabsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> MOSSY_ANDESITE_BRICK_STAIRS = block("mossy_andesite_brick_stairs", () -> new StairsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> MOSSY_ANDESITE_BRICK_WALL = block("mossy_andesite_brick_wall", () -> new WallsBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> MOSSY_ANDESITE_BRICK_VERTICAL_SLAB = block("mossy_andesite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> CHISELED_ANDESITE = block("chiseled_andesite", () -> new BuildingBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> ANDESITE_PILLAR = block("andesite_pillar", () -> new PillarBlock(Blocks.POLISHED_ANDESITE));

    public static final RegistrySupplier<Block> POLISHED_DIORITE_WALL = block("polished_diorite_wall", () -> new WallsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> SMOOTH_DIORITE = block("smooth_diorite", () -> new BuildingBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> SMOOTH_DIORITE_SLAB = block("smooth_diorite_slab", () -> new SlabsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> SMOOTH_DIORITE_STAIRS = block("smooth_diorite_stairs", () -> new StairsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> SMOOTH_DIORITE_WALL = block("smooth_diorite_wall", () -> new WallsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> SMOOTH_DIORITE_VERTICAL_SLAB = block("smooth_diorite_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> DIORITE_BRICKS = block("diorite_bricks", () -> new BuildingBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> DIORITE_BRICK_SLAB = block("diorite_brick_slab", () -> new SlabsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> DIORITE_BRICK_STAIRS = block("diorite_brick_stairs", () -> new StairsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> DIORITE_BRICK_WALL = block("diorite_brick_wall", () -> new WallsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> DIORITE_BRICK_VERTICAL_SLAB = block("diorite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> CRACKED_DIORITE_BRICKS = block("cracked_diorite_bricks", () -> new BuildingBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> CRACKED_DIORITE_BRICK_SLAB = block("cracked_diorite_brick_slab", () -> new SlabsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> CRACKED_DIORITE_BRICK_STAIRS = block("cracked_diorite_brick_stairs", () -> new StairsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> CRACKED_DIORITE_BRICK_WALL = block("cracked_diorite_brick_wall", () -> new WallsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> CRACKED_DIORITE_BRICK_VERTICAL_SLAB = block("cracked_diorite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> MOSSY_DIORITE_BRICKS = block("mossy_diorite_bricks", () -> new BuildingBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> MOSSY_DIORITE_BRICK_SLAB = block("mossy_diorite_brick_slab", () -> new SlabsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> MOSSY_DIORITE_BRICK_STAIRS = block("mossy_diorite_brick_stairs", () -> new StairsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> MOSSY_DIORITE_BRICK_WALL = block("mossy_diorite_brick_wall", () -> new WallsBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> MOSSY_DIORITE_BRICK_VERTICAL_SLAB = block("mossy_diorite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> CHISELED_DIORITE = block("chiseled_diorite", () -> new BuildingBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> DIORITE_PILLAR = block("diorite_pillar", () -> new PillarBlock(Blocks.POLISHED_GRANITE));

    public static final RegistrySupplier<Block> POLISHED_GRANITE_WALL = block("polished_granite_wall", () -> new WallsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> SMOOTH_GRANITE = block("smooth_granite", () -> new BuildingBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> SMOOTH_GRANITE_SLAB = block("smooth_granite_slab", () -> new SlabsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> SMOOTH_GRANITE_STAIRS = block("smooth_granite_stairs", () -> new StairsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> SMOOTH_GRANITE_WALL = block("smooth_granite_wall", () -> new WallsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> SMOOTH_GRANITE_VERTICAL_SLAB = block("smooth_granite_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> GRANITE_BRICKS = block("granite_bricks", () -> new BuildingBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> GRANITE_BRICK_SLAB = block("granite_brick_slab", () -> new SlabsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> GRANITE_BRICK_STAIRS = block("granite_brick_stairs", () -> new StairsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> GRANITE_BRICK_WALL = block("granite_brick_wall", () -> new WallsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> GRANITE_BRICK_VERTICAL_SLAB = block("granite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> CRACKED_GRANITE_BRICKS = block("cracked_granite_bricks", () -> new BuildingBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> CRACKED_GRANITE_BRICK_SLAB = block("cracked_granite_brick_slab", () -> new SlabsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> CRACKED_GRANITE_BRICK_STAIRS = block("cracked_granite_brick_stairs", () -> new StairsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> CRACKED_GRANITE_BRICK_WALL = block("cracked_granite_brick_wall", () -> new WallsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> CRACKED_GRANITE_BRICK_VERTICAL_SLAB = block("cracked_granite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> MOSSY_GRANITE_BRICKS = block("mossy_granite_bricks", () -> new BuildingBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> MOSSY_GRANITE_BRICK_SLAB = block("mossy_granite_brick_slab", () -> new SlabsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> MOSSY_GRANITE_BRICK_STAIRS = block("mossy_granite_brick_stairs", () -> new StairsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> MOSSY_GRANITE_BRICK_WALL = block("mossy_granite_brick_wall", () -> new WallsBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> MOSSY_GRANITE_BRICK_VERTICAL_SLAB = block("mossy_granite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> CHISELED_GRANITE = block("chiseled_granite", () -> new BuildingBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> GRANITE_PILLAR = block("granite_pillar", () -> new PillarBlock(Blocks.POLISHED_GRANITE));

    public static final RegistrySupplier<Block> POLISHED_SMOOTH_BASALT = block("polished_smooth_basalt", () -> new BuildingBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> POLISHED_SMOOTH_BASALT_SLAB = block("polished_smooth_basalt_slab", () -> new SlabsBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> POLISHED_SMOOTH_BASALT_STAIRS = block("polished_smooth_basalt_stairs", () -> new StairsBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> POLISHED_SMOOTH_BASALT_WALL = block("polished_smooth_basalt_wall", () -> new WallsBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> POLISHED_SMOOTH_BASALT_VERTICAL_SLAB = block("polished_smooth_basalt_vertical_slab", () -> new VerticalSlabBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> SMOOTH_BASALT_BRICKS = block("smooth_basalt_bricks", () -> new BuildingBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> SMOOTH_BASALT_BRICK_SLAB = block("smooth_basalt_brick_slab", () -> new SlabsBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> SMOOTH_BASALT_BRICK_STAIRS = block("smooth_basalt_brick_stairs", () -> new StairsBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> SMOOTH_BASALT_BRICK_WALL = block("smooth_basalt_brick_wall", () -> new WallsBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> SMOOTH_BASALT_BRICK_VERTICAL_SLAB = block("smooth_basalt_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> CRACKED_SMOOTH_BASALT_BRICKS = block("cracked_smooth_basalt_bricks", () -> new BuildingBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> CRACKED_SMOOTH_BASALT_BRICK_SLAB = block("cracked_smooth_basalt_brick_slab", () -> new SlabsBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> CRACKED_SMOOTH_BASALT_BRICK_STAIRS = block("cracked_smooth_basalt_brick_stairs", () -> new StairsBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> CRACKED_SMOOTH_BASALT_BRICK_WALL = block("cracked_smooth_basalt_brick_wall", () -> new WallsBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> CRACKED_SMOOTH_BASALT_BRICK_VERTICAL_SLAB = block("cracked_smooth_basalt_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> CHISELED_SMOOTH_BASALT = block("chiseled_smooth_basalt", () -> new BuildingBlock(Blocks.SMOOTH_BASALT));
    public static final RegistrySupplier<Block> SMOOTH_BASALT_PILLAR = block("smooth_basalt_pillar", () -> new PillarBlock(Blocks.SMOOTH_BASALT));

    public static final RegistrySupplier<Block> POLISHED_DRIPSTONE = block("polished_dripstone", () -> new BuildingBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> POLISHED_DRIPSTONE_SLAB = block("polished_dripstone_slab", () -> new SlabsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> POLISHED_DRIPSTONE_STAIRS = block("polished_dripstone_stairs", () -> new StairsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> POLISHED_DRIPSTONE_WALL = block("polished_dripstone_wall", () -> new WallsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> POLISHED_DRIPSTONE_VERTICAL_SLAB = block("polished_dripstone_vertical_slab", () -> new VerticalSlabBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_BRICKS = block("dripstone_bricks", () -> new BuildingBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_BRICK_SLAB = block("dripstone_brick_slab", () -> new SlabsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_BRICK_STAIRS = block("dripstone_brick_stairs", () -> new StairsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_BRICK_WALL = block("dripstone_brick_wall", () -> new WallsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_BRICK_VERTICAL_SLAB = block("dripstone_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CRACKED_DRIPSTONE_BRICKS = block("cracked_dripstone_bricks", () -> new BuildingBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CRACKED_DRIPSTONE_BRICK_SLAB = block("cracked_dripstone_brick_slab", () -> new SlabsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CRACKED_DRIPSTONE_BRICK_STAIRS = block("cracked_dripstone_brick_stairs", () -> new StairsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CRACKED_DRIPSTONE_BRICK_WALL = block("cracked_dripstone_brick_wall", () -> new WallsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CRACKED_DRIPSTONE_BRICK_VERTICAL_SLAB = block("cracked_dripstone_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_TILES = block("dripstone_tiles", () -> new BuildingBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_TILE_SLAB = block("dripstone_tile_slab", () -> new SlabsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_TILE_STAIRS = block("dripstone_tile_stairs", () -> new StairsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_TILE_WALL = block("dripstone_tile_wall", () -> new WallsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_TILE_VERTICAL_SLAB = block("dripstone_tile_vertical_slab", () -> new VerticalSlabBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CRACKED_DRIPSTONE_TILES = block("cracked_dripstone_tiles", () -> new BuildingBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CRACKED_DRIPSTONE_TILE_SLAB = block("cracked_dripstone_tile_slab", () -> new SlabsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CRACKED_DRIPSTONE_TILE_STAIRS = block("cracked_dripstone_tile_stairs", () -> new StairsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CRACKED_DRIPSTONE_TILE_WALL = block("cracked_dripstone_tile_wall", () -> new WallsBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CRACKED_DRIPSTONE_TILE_VERTICAL_SLAB = block("cracked_dripstone_tile_vertical_slab", () -> new VerticalSlabBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> CHISELED_DRIPSTONE = block("chiseled_dripstone", () -> new BuildingBlock(Blocks.DRIPSTONE_BLOCK));
    public static final RegistrySupplier<Block> DRIPSTONE_PILLAR = block("dripstone_pillar", () -> new PillarBlock(Blocks.DRIPSTONE_BLOCK));

    public static final RegistrySupplier<Block> POLISHED_CALCITE = block("polished_calcite", () -> new BuildingBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> POLISHED_CALCITE_SLAB = block("polished_calcite_slab", () -> new SlabsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> POLISHED_CALCITE_STAIRS = block("polished_calcite_stairs", () -> new StairsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> POLISHED_CALCITE_WALL = block("polished_calcite_wall", () -> new WallsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> POLISHED_CALCITE_VERTICAL_SLAB = block("polished_calcite_vertical_slab", () -> new VerticalSlabBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CALCITE_BRICKS = block("calcite_bricks", () -> new BuildingBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CALCITE_BRICK_SLAB = block("calcite_brick_slab", () -> new SlabsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CALCITE_BRICK_STAIRS = block("calcite_brick_stairs", () -> new StairsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CALCITE_BRICK_WALL = block("calcite_brick_wall", () -> new WallsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CALCITE_BRICK_VERTICAL_SLAB = block("calcite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CRACKED_CALCITE_BRICKS = block("cracked_calcite_bricks", () -> new BuildingBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CRACKED_CALCITE_BRICK_SLAB = block("cracked_calcite_brick_slab", () -> new SlabsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CRACKED_CALCITE_BRICK_STAIRS = block("cracked_calcite_brick_stairs", () -> new StairsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CRACKED_CALCITE_BRICK_WALL = block("cracked_calcite_brick_wall", () -> new WallsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CRACKED_CALCITE_BRICK_VERTICAL_SLAB = block("cracked_calcite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CHISELED_CALCITE = block("chiseled_calcite", () -> new BuildingBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CALCITE_PILLAR = block("calcite_pillar", () -> new PillarBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE = block("smooth_calcite", () -> new BuildingBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE_SLAB = block("smooth_calcite_slab", () -> new SlabsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE_STAIRS = block("smooth_calcite_stairs", () -> new StairsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE_WALL = block("smooth_calcite_wall", () -> new WallsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE_VERTICAL_SLAB = block("smooth_calcite_vertical_slab", () -> new VerticalSlabBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE_BRICKS = block("smooth_calcite_bricks", () -> new BuildingBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE_BRICK_SLAB = block("smooth_calcite_brick_slab", () -> new SlabsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE_BRICK_STAIRS = block("smooth_calcite_brick_stairs", () -> new StairsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE_BRICK_WALL = block("smooth_calcite_brick_wall", () -> new WallsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE_BRICK_VERTICAL_SLAB = block("smooth_calcite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CRACKED_SMOOTH_CALCITE_BRICKS = block("cracked_smooth_calcite_bricks", () -> new BuildingBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CRACKED_SMOOTH_CALCITE_BRICK_SLAB = block("cracked_smooth_calcite_brick_slab", () -> new SlabsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CRACKED_SMOOTH_CALCITE_BRICK_STAIRS = block("cracked_smooth_calcite_brick_stairs", () -> new StairsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CRACKED_SMOOTH_CALCITE_BRICK_WALL = block("cracked_smooth_calcite_brick_wall", () -> new WallsBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CRACKED_SMOOTH_CALCITE_BRICK_VERTICAL_SLAB = block("cracked_smooth_calcite_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> CHISELED_SMOOTH_CALCITE = block("chiseled_smooth_calcite", () -> new BuildingBlock(Blocks.CALCITE));
    public static final RegistrySupplier<Block> SMOOTH_CALCITE_PILLAR = block("smooth_calcite_pillar", () -> new PillarBlock(Blocks.CALCITE));

    public static final RegistrySupplier<Block> QUARTZ_BRICK_SLAB = block("quartz_brick_slab", () -> new SlabsBlock(Blocks.QUARTZ_BRICKS));
    public static final RegistrySupplier<Block> QUARTZ_BRICK_STAIRS = block("quartz_brick_stairs", () -> new StairsBlock(Blocks.QUARTZ_BRICKS));
    public static final RegistrySupplier<Block> QUARTZ_BRICK_WALL = block("quartz_brick_wall", () -> new WallsBlock(Blocks.QUARTZ_BRICKS));
    public static final RegistrySupplier<Block> QUARTZ_BRICK_VERTICAL_SLAB = block("quartz_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.QUARTZ_BRICKS));

    public static final RegistrySupplier<Block> PRISMARINE_TILES = block("prismarine_tiles", () -> new BuildingBlock(Blocks.PRISMARINE));
    public static final RegistrySupplier<Block> PRISMARINE_TILE_SLAB = block("prismarine_tile_slab", () -> new SlabsBlock(Blocks.PRISMARINE));
    public static final RegistrySupplier<Block> PRISMARINE_TILE_STAIRS = block("prismarine_tile_stairs", () -> new StairsBlock(Blocks.PRISMARINE));
    public static final RegistrySupplier<Block> PRISMARINE_TILE_WALL = block("prismarine_tile_wall", () -> new WallsBlock(Blocks.PRISMARINE));
    public static final RegistrySupplier<Block> PRISMARINE_TILE_VERTICAL_SLAB = block("prismarine_tile_vertical_slab", () -> new VerticalSlabBlock(Blocks.PRISMARINE));
    public static final RegistrySupplier<Block> PRISMARINE_BRICK_WALL = block("prismarine_brick_wall", () -> new WallsBlock(Blocks.PRISMARINE));
    public static final RegistrySupplier<Block> DARK_PRISMARINE_WALL = block("dark_prismarine_wall", () -> new WallsBlock(Blocks.DARK_PRISMARINE));

    public static final RegistrySupplier<Block> SOUL_CANDLE = block("soul_candle", () -> new CandlesBlock(MapColor.SAND));
    public static final RegistrySupplier<Block> SOUL_WHITE_CANDLE = block("soul_white_candle", () -> new CandlesBlock(MapColor.WOOL));
    public static final RegistrySupplier<Block> SOUL_ORANGE_CANDLE = block("soul_orange_candle", () -> new CandlesBlock(MapColor.COLOR_ORANGE));
    public static final RegistrySupplier<Block> SOUL_MAGENTA_CANDLE = block("soul_magenta_candle", () -> new CandlesBlock(MapColor.COLOR_MAGENTA));
    public static final RegistrySupplier<Block> SOUL_LIGHT_BLUE_CANDLE = block("soul_light_blue_candle", () -> new CandlesBlock(MapColor.COLOR_LIGHT_BLUE));
    public static final RegistrySupplier<Block> SOUL_YELLOW_CANDLE = block("soul_yellow_candle", () -> new CandlesBlock(MapColor.COLOR_YELLOW));
    public static final RegistrySupplier<Block> SOUL_LIME_CANDLE = block("soul_lime_candle", () -> new CandlesBlock(MapColor.COLOR_LIGHT_GREEN));
    public static final RegistrySupplier<Block> SOUL_PINK_CANDLE = block("soul_pink_candle", () -> new CandlesBlock(MapColor.COLOR_PINK));
    public static final RegistrySupplier<Block> SOUL_GRAY_CANDLE = block("soul_gray_candle", () -> new CandlesBlock(MapColor.COLOR_GRAY));
    public static final RegistrySupplier<Block> SOUL_LIGHT_GRAY_CANDLE = block("soul_light_gray_candle", () -> new CandlesBlock(MapColor.COLOR_LIGHT_GRAY));
    public static final RegistrySupplier<Block> SOUL_CYAN_CANDLE = block("soul_cyan_candle", () -> new CandlesBlock(MapColor.COLOR_CYAN));
    public static final RegistrySupplier<Block> SOUL_PURPLE_CANDLE = block("soul_purple_candle", () -> new CandlesBlock(MapColor.COLOR_PURPLE));
    public static final RegistrySupplier<Block> SOUL_BLUE_CANDLE = block("soul_blue_candle", () -> new CandlesBlock(MapColor.COLOR_BLUE));
    public static final RegistrySupplier<Block> SOUL_BROWN_CANDLE = block("soul_brown_candle", () -> new CandlesBlock(MapColor.COLOR_BROWN));
    public static final RegistrySupplier<Block> SOUL_GREEN_CANDLE = block("soul_green_candle", () -> new CandlesBlock(MapColor.COLOR_GREEN));
    public static final RegistrySupplier<Block> SOUL_RED_CANDLE = block("soul_red_candle", () -> new CandlesBlock(MapColor.COLOR_RED));
    public static final RegistrySupplier<Block> SOUL_BLACK_CANDLE = block("soul_black_candle", () -> new CandlesBlock(MapColor.COLOR_BLACK));

    public static final RegistrySupplier<Block> SOUL_CANDLE_CAKE = blockOnly("soul_candle_cake", () -> new CandlesCakeBlock(SOUL_CANDLE));
    public static final RegistrySupplier<Block> SOUL_WHITE_CANDLE_CAKE = blockOnly("soul_white_candle_cake", () -> new CandlesCakeBlock(SOUL_WHITE_CANDLE));
    public static final RegistrySupplier<Block> SOUL_ORANGE_CANDLE_CAKE = blockOnly("soul_orange_candle_cake", () -> new CandlesCakeBlock(SOUL_ORANGE_CANDLE));
    public static final RegistrySupplier<Block> SOUL_MAGENTA_CANDLE_CAKE = blockOnly("soul_magenta_candle_cake", () -> new CandlesCakeBlock(SOUL_MAGENTA_CANDLE));
    public static final RegistrySupplier<Block> SOUL_LIGHT_BLUE_CANDLE_CAKE = blockOnly("soul_light_blue_candle_cake", () -> new CandlesCakeBlock(SOUL_LIGHT_BLUE_CANDLE));
    public static final RegistrySupplier<Block> SOUL_YELLOW_CANDLE_CAKE = blockOnly("soul_yellow_candle_cake", () -> new CandlesCakeBlock(SOUL_YELLOW_CANDLE));
    public static final RegistrySupplier<Block> SOUL_LIME_CANDLE_CAKE = blockOnly("soul_lime_candle_cake", () -> new CandlesCakeBlock(SOUL_LIME_CANDLE));
    public static final RegistrySupplier<Block> SOUL_PINK_CANDLE_CAKE = blockOnly("soul_pink_candle_cake", () -> new CandlesCakeBlock(SOUL_PINK_CANDLE));
    public static final RegistrySupplier<Block> SOUL_GRAY_CANDLE_CAKE = blockOnly("soul_gray_candle_cake", () -> new CandlesCakeBlock(SOUL_GRAY_CANDLE));
    public static final RegistrySupplier<Block> SOUL_LIGHT_GRAY_CANDLE_CAKE = blockOnly("soul_light_gray_candle_cake", () -> new CandlesCakeBlock(SOUL_LIGHT_GRAY_CANDLE));
    public static final RegistrySupplier<Block> SOUL_CYAN_CANDLE_CAKE = blockOnly("soul_cyan_candle_cake", () -> new CandlesCakeBlock(SOUL_CYAN_CANDLE));
    public static final RegistrySupplier<Block> SOUL_PURPLE_CANDLE_CAKE = blockOnly("soul_purple_candle_cake", () -> new CandlesCakeBlock(SOUL_PURPLE_CANDLE));
    public static final RegistrySupplier<Block> SOUL_BLUE_CANDLE_CAKE = blockOnly("soul_blue_candle_cake", () -> new CandlesCakeBlock(SOUL_BLUE_CANDLE));
    public static final RegistrySupplier<Block> SOUL_BROWN_CANDLE_CAKE = blockOnly("soul_brown_candle_cake", () -> new CandlesCakeBlock(SOUL_BROWN_CANDLE));
    public static final RegistrySupplier<Block> SOUL_GREEN_CANDLE_CAKE = blockOnly("soul_green_candle_cake", () -> new CandlesCakeBlock(SOUL_GREEN_CANDLE));
    public static final RegistrySupplier<Block> SOUL_RED_CANDLE_CAKE = blockOnly("soul_red_candle_cake", () -> new CandlesCakeBlock(SOUL_RED_CANDLE));
    public static final RegistrySupplier<Block> SOUL_BLACK_CANDLE_CAKE = blockOnly("soul_black_candle_cake", () -> new CandlesCakeBlock(SOUL_BLACK_CANDLE));

    public static final RegistrySupplier<Block> ACACIA_CAVITY = block("acacia_cavity", () -> new CavityLog(Blocks.ACACIA_LOG));
    public static final RegistrySupplier<Block> BIRCH_CAVITY = block("birch_cavity", () -> new CavityLog(Blocks.BIRCH_LOG));
    public static final RegistrySupplier<Block> CHERRY_CAVITY = block("cherry_cavity", () -> new CavityLog(Blocks.CHERRY_LOG));
    public static final RegistrySupplier<Block> DARK_OAK_CAVITY = block("dark_oak_cavity", () -> new CavityLog(Blocks.DARK_OAK_LOG));
    public static final RegistrySupplier<Block> JUNGLE_CAVITY = block("jungle_cavity", () -> new CavityLog(Blocks.JUNGLE_LOG));
    public static final RegistrySupplier<Block> MANGROVE_CAVITY = block("mangrove_cavity", () -> new CavityLog(Blocks.MANGROVE_LOG));
    public static final RegistrySupplier<Block> OAK_CAVITY = block("oak_cavity", () -> new CavityLog(Blocks.OAK_LOG));
    public static final RegistrySupplier<Block> SPRUCE_CAVITY = block("spruce_cavity", () -> new CavityLog(Blocks.SPRUCE_LOG));

    public static final RegistrySupplier<Block> PEONY = block("peony", () -> new PlantBlock(MobEffects.WEAKNESS, 7));
    public static final RegistrySupplier<Block> LILAC = block("lilac", () -> new PlantBlock(MobEffects.REGENERATION, 4));
    public static final RegistrySupplier<Block> HYACINTH = block("hyacinth", () -> new PlantBlock(MobEffects.POISON, 8));
    public static final RegistrySupplier<Block> LAPIS_LOTUS = block("lapis_lotus", () -> new PlantBlock(MobEffects.NIGHT_VISION, 10));
    public static final RegistrySupplier<Block> GOLDEN_POPPY = block("golden_poppy", () -> new PlantBlock(MobEffects.HARM, 4));
    public static final RegistrySupplier<Block> ROSE = block("rose", () -> new PlantBlock(MobEffects.MOVEMENT_SPEED, 4));
    public static final RegistrySupplier<Block> CYAN_ROSE = block("cyan_rose", () -> new PlantBlock(MobEffects.MOVEMENT_SPEED, 5));
    public static final RegistrySupplier<Block> HELIOTROPE = block("heliotrope", () -> new PlantBlock(MobEffects.REGENERATION, 5));

    public static final RegistrySupplier<Block> CYAN_ROSE_BUSH = block("cyan_rose_bush", TallPlantBlock::new);
    public static final RegistrySupplier<Block> MARIGOLD = block("marigold", TallPlantBlock::new);
    public static final RegistrySupplier<Block> TALL_DEAD_BUSH = block("tall_dead_bush", TallDeadBushBlock::new, 200);

    public static final RegistrySupplier<Block> PUFFBALLS = block("puffballs", PlantBlock::new);
    public static final RegistrySupplier<Block> MYCELIUM_ROOTS = block("mycelium_roots", () -> new NetherRootsBlock(MapColor.COLOR_GRAY));
    public static final RegistrySupplier<Block> MYCELIUM_SPROUTS = block("mycelium_sprouts", () -> new SproutsBlock(MapColor.COLOR_GRAY));
    public static final RegistrySupplier<Block> MUSHROOM_CLUSTER = block("mushroom_cluster", PlantBlock::new);
    public static final RegistrySupplier<Block> RED_MUSHROOM_CLUSTER = block("red_mushroom_cluster", PlantBlock::new);
    public static final RegistrySupplier<Block> BROWN_MUSHROOM_CLUSTER = block("brown_mushroom_cluster", PlantBlock::new);
    public static final RegistrySupplier<Block> TALL_RED_MUSHROOM_CLUSTER = block("tall_red_mushroom_cluster", TallPlantBlock::new);
    public static final RegistrySupplier<Block> TALL_BROWN_MUSHROOM_CLUSTER = block("tall_brown_mushroom_cluster", TallPlantBlock::new);

    public static final RegistrySupplier<Block> POTTED_PEONY = blockOnly("potted_peony", () -> new FlowerPotsBlock(PEONY));
    public static final RegistrySupplier<Block> POTTED_LILAC = blockOnly("potted_lilac", () -> new FlowerPotsBlock(LILAC));
    public static final RegistrySupplier<Block> POTTED_HYACINTH = blockOnly("potted_hyacinth", () -> new FlowerPotsBlock(HYACINTH));
    public static final RegistrySupplier<Block> POTTED_LAPIS_LOTUS = blockOnly("potted_lapis_lotus", () -> new FlowerPotsBlock(LAPIS_LOTUS));
    public static final RegistrySupplier<Block> POTTED_GOLDEN_POPPY = blockOnly("potted_golden_poppy", () -> new FlowerPotsBlock(GOLDEN_POPPY));
    public static final RegistrySupplier<Block> POTTED_ROSE = blockOnly("potted_rose", () -> new FlowerPotsBlock(ROSE));
    public static final RegistrySupplier<Block> POTTED_CYAN_ROSE = blockOnly("potted_cyan_rose", () -> new FlowerPotsBlock(CYAN_ROSE));
    public static final RegistrySupplier<Block> POTTED_PUFFBALLS = blockOnly("potted_puffballs", () -> new FlowerPotsBlock(PUFFBALLS));
    public static final RegistrySupplier<Block> POTTED_MYCELIUM_ROOTS = blockOnly("potted_mycelium_roots", () -> new FlowerPotsBlock(MYCELIUM_ROOTS));
    public static final RegistrySupplier<Block> POTTED_MUSHROOM_CLUSTER = blockOnly("potted_mushroom_cluster", () -> new FlowerPotsBlock(MUSHROOM_CLUSTER));
    public static final RegistrySupplier<Block> POTTED_BROWN_MUSHROOM_CLUSTER = blockOnly("potted_brown_mushroom_cluster", () -> new FlowerPotsBlock(BROWN_MUSHROOM_CLUSTER));
    public static final RegistrySupplier<Block> POTTED_RED_MUSHROOM_CLUSTER = blockOnly("potted_red_mushroom_cluster", () -> new FlowerPotsBlock(RED_MUSHROOM_CLUSTER));
    public static final RegistrySupplier<Block> POTTED_HELIOTROPE = blockOnly("potted_heliotrope", () -> new FlowerPotsBlock(HELIOTROPE.get()));

    public static final RegistrySupplier<Block> POTTED_LARGE_FERN = blockOnly("potted_large_fern", () -> new FlowerPotsBlock(Blocks.LARGE_FERN));
    public static final RegistrySupplier<Block> POTTED_TWISTING_VINES = blockOnly("potted_twisting_vines", () -> new FlowerPotsBlock(Blocks.TWISTING_VINES));
    public static final RegistrySupplier<Block> POTTED_WEEPING_VINES = blockOnly("potted_weeping_vines", () -> new FlowerPotsBlock(Blocks.WEEPING_VINES));
    public static final RegistrySupplier<Block> POTTED_CRIMSON_SPROUTS = blockOnly("potted_crimson_sprouts", () -> new FlowerPotsBlock(CRIMSON_SPROUTS));
    public static final RegistrySupplier<Block> POTTED_VERDANT_SPROUTS = blockOnly("potted_verdant_sprouts", () -> new FlowerPotsBlock(VERDANT_SPROUTS));
    public static final RegistrySupplier<Block> POTTED_WARPED_SPROUTS = blockOnly("potted_warped_sprouts", () -> new FlowerPotsBlock(Blocks.NETHER_SPROUTS));

    public static final RegistrySupplier<Block> MOSSY_COBBLED_DEEPSLATE = block("mossy_cobbled_deepslate", () -> new BuildingBlock(Blocks.COBBLED_DEEPSLATE));
    public static final RegistrySupplier<Block> MOSSY_COBBLED_DEEPSLATE_SLAB = block("mossy_cobbled_deepslate_slab", () -> new SlabsBlock(Blocks.COBBLED_DEEPSLATE));
    public static final RegistrySupplier<Block> MOSSY_COBBLED_DEEPSLATE_STAIRS = block("mossy_cobbled_deepslate_stairs", () -> new StairsBlock(Blocks.COBBLED_DEEPSLATE));
    public static final RegistrySupplier<Block> MOSSY_COBBLED_DEEPSLATE_WALL = block("mossy_cobbled_deepslate_wall", () -> new WallsBlock(Blocks.COBBLED_DEEPSLATE));
    public static final RegistrySupplier<Block> MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB = block("mossy_cobbled_deepslate_vertical_slab", () -> new VerticalSlabBlock(Blocks.COBBLED_DEEPSLATE));

    public static final RegistrySupplier<Block> ACACIA_VERTICAL_SLAB = block("acacia_vertical_slab", () -> new VerticalSlabBlock(Blocks.ACACIA_PLANKS), 150);
    public static final RegistrySupplier<Block> BAMBOO_VERTICAL_SLAB = block("bamboo_vertical_slab", () -> new VerticalSlabBlock(Blocks.BAMBOO_PLANKS), 150);
    public static final RegistrySupplier<Block> BIRCH_VERTICAL_SLAB = block("birch_vertical_slab", () -> new VerticalSlabBlock(Blocks.BIRCH_PLANKS), 150);
    public static final RegistrySupplier<Block> CHERRY_VERTICAL_SLAB = block("cherry_vertical_slab", () -> new VerticalSlabBlock(Blocks.CHERRY_PLANKS), 150);
    public static final RegistrySupplier<Block> CRIMSON_VERTICAL_SLAB = block("crimson_vertical_slab", () -> new VerticalSlabBlock(Blocks.CRIMSON_PLANKS));
    public static final RegistrySupplier<Block> DARK_OAK_VERTICAL_SLAB = block("dark_oak_vertical_slab", () -> new VerticalSlabBlock(Blocks.DARK_OAK_PLANKS), 150);
    public static final RegistrySupplier<Block> JUNGLE_VERTICAL_SLAB = block("jungle_vertical_slab", () -> new VerticalSlabBlock(Blocks.JUNGLE_PLANKS), 150);
    public static final RegistrySupplier<Block> MANGROVE_VERTICAL_SLAB = block("mangrove_vertical_slab", () -> new VerticalSlabBlock(Blocks.MANGROVE_PLANKS), 150);
    public static final RegistrySupplier<Block> OAK_VERTICAL_SLAB = block("oak_vertical_slab", () -> new VerticalSlabBlock(Blocks.OAK_PLANKS), 150);
    public static final RegistrySupplier<Block> SPRUCE_VERTICAL_SLAB = block("spruce_vertical_slab", () -> new VerticalSlabBlock(Blocks.SPRUCE_PLANKS), 150);
    public static final RegistrySupplier<Block> VERDANT_VERTICAL_SLAB = block("verdant_vertical_slab", () -> new VerticalSlabBlock(VERDANT_PLANKS));
    public static final RegistrySupplier<Block> WARPED_VERTICAL_SLAB = block("warped_vertical_slab", () -> new VerticalSlabBlock(Blocks.WARPED_PLANKS));

    public static final RegistrySupplier<Block> STONE_VERTICAL_SLAB = block("stone_vertical_slab", () -> new VerticalSlabBlock(Blocks.STONE));
    public static final RegistrySupplier<Block> COBBLESTONE_VERTICAL_SLAB = block("cobblestone_vertical_slab", () -> new VerticalSlabBlock(Blocks.COBBLESTONE));
    public static final RegistrySupplier<Block> MOSSY_COBBLESTONE_VERTICAL_SLAB = block("mossy_cobblestone_vertical_slab", () -> new VerticalSlabBlock(Blocks.MOSSY_COBBLESTONE));
    public static final RegistrySupplier<Block> GRANITE_VERTICAL_SLAB = block("granite_vertical_slab", () -> new VerticalSlabBlock(Blocks.GRANITE));
    public static final RegistrySupplier<Block> DIORITE_VERTICAL_SLAB = block("diorite_vertical_slab", () -> new VerticalSlabBlock(Blocks.DIORITE));
    public static final RegistrySupplier<Block> ANDESITE_VERTICAL_SLAB = block("andesite_vertical_slab", () -> new VerticalSlabBlock(Blocks.ANDESITE));
    public static final RegistrySupplier<Block> POLISHED_GRANITE_VERTICAL_SLAB = block("polished_granite_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_GRANITE));
    public static final RegistrySupplier<Block> POLISHED_DIORITE_VERTICAL_SLAB = block("polished_diorite_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_DIORITE));
    public static final RegistrySupplier<Block> POLISHED_ANDESITE_VERTICAL_SLAB = block("polished_andesite_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_ANDESITE));
    public static final RegistrySupplier<Block> COBBLED_DEEPSLATE_VERTICAL_SLAB = block("cobbled_deepslate_vertical_slab", () -> new VerticalSlabBlock(Blocks.COBBLED_DEEPSLATE));
    public static final RegistrySupplier<Block> POLISHED_DEEPSLATE_VERTICAL_SLAB = block("polished_deepslate_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_DEEPSLATE));
    public static final RegistrySupplier<Block> PRISMARINE_VERTICAL_SLAB = block("prismarine_vertical_slab", () -> new VerticalSlabBlock(Blocks.PRISMARINE));
    public static final RegistrySupplier<Block> DARK_PRISMARINE_VERTICAL_SLAB = block("dark_prismarine_vertical_slab", () -> new VerticalSlabBlock(Blocks.DARK_PRISMARINE));

    public static final RegistrySupplier<Block> STONE_BRICK_VERTICAL_SLAB = block("stone_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.STONE_BRICKS));
    public static final RegistrySupplier<Block> MOSSY_STONE_BRICK_VERTICAL_SLAB = block("mossy_stone_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.MOSSY_STONE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_STONE_BRICK_VERTICAL_SLAB = block("cracked_stone_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.CRACKED_STONE_BRICKS));
    public static final RegistrySupplier<Block> DEEPSLATE_BRICK_VERTICAL_SLAB = block("deepslate_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.DEEPSLATE_BRICKS));
    public static final RegistrySupplier<Block> DEEPSLATE_TILE_VERTICAL_SLAB = block("deepslate_tile_vertical_slab", () -> new VerticalSlabBlock(Blocks.DEEPSLATE_TILES));
    public static final RegistrySupplier<Block> CRACKED_DEEPSLATE_BRICK_VERTICAL_SLAB = block("cracked_deepslate_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.CRACKED_DEEPSLATE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_DEEPSLATE_TILE_VERTICAL_SLAB = block("cracked_deepslate_tile_vertical_slab", () -> new VerticalSlabBlock(Blocks.CRACKED_DEEPSLATE_TILES));
    public static final RegistrySupplier<Block> BRICK_VERTICAL_SLAB = block("brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.BRICKS));
    public static final RegistrySupplier<Block> MUD_BRICK_BRICK_VERTICAL_SLAB = block("mud_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.MUD_BRICKS));
    public static final RegistrySupplier<Block> PRISMARINE_BRICK_VERTICAL_SLAB = block("prismarine_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.PRISMARINE_BRICKS));
    public static final RegistrySupplier<Block> NETHER_BRICK_VERTICAL_SLAB = block("nether_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.NETHER_BRICKS));
    public static final RegistrySupplier<Block> RED_NETHER_BRICK_VERTICAL_SLAB = block("red_nether_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.RED_NETHER_BRICKS));

    public static final RegistrySupplier<Block> SANDSTONE_VERTICAL_SLAB = block("sandstone_vertical_slab", () -> new VerticalSlabBlock(Blocks.SANDSTONE));
    public static final RegistrySupplier<Block> RED_SANDSTONE_VERTICAL_SLAB = block("red_sandstone_vertical_slab", () -> new VerticalSlabBlock(Blocks.RED_SANDSTONE));
    public static final RegistrySupplier<Block> QUARTZ_VERTICAL_SLAB = block("quartz_vertical_slab", () -> new VerticalSlabBlock(Blocks.QUARTZ_BLOCK));
    public static final RegistrySupplier<Block> SMOOTH_QUARTZ_VERTICAL_SLAB = block("smooth_quartz_vertical_slab", () -> new VerticalSlabBlock(Blocks.SMOOTH_QUARTZ));
    public static final RegistrySupplier<Block> BLACKSTONE_VERTICAL_SLAB = block("blackstone_vertical_slab", () -> new VerticalSlabBlock(Blocks.BLACKSTONE));
    public static final RegistrySupplier<Block> POLISHED_BLACKSTONE_VERTICAL_SLAB = block("polished_blackstone_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_BLACKSTONE));
    public static final RegistrySupplier<Block> POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB = block("polished_blackstone_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_BLACKSTONE_BRICKS));
    public static final RegistrySupplier<Block> CRACKED_POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB = block("cracked_polished_blackstone_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS));
    public static final RegistrySupplier<Block> ENDSTONE_BRICK_VERTICAL_SLAB = block("end_stone_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.END_STONE_BRICKS));
    public static final RegistrySupplier<Block> PURPUR_VERTICAL_SLAB = block("purpur_vertical_slab", () -> new VerticalSlabBlock(Blocks.PURPUR_BLOCK));

    public static final RegistrySupplier<Block> VERTICAL_ACACIA_PLANK_VERTICAL_SLAB = block("vertical_acacia_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.ACACIA_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_BAMBOO_PLANK_VERTICAL_SLAB = block("vertical_bamboo_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.BAMBOO_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_BIRCH_PLANK_VERTICAL_SLAB = block("vertical_birch_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.BIRCH_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_CHERRY_PLANK_VERTICAL_SLAB = block("vertical_cherry_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.CHERRY_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_CRIMSON_PLANK_VERTICAL_SLAB = block("vertical_crimson_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.CRIMSON_PLANKS));
    public static final RegistrySupplier<Block> VERTICAL_DARK_OAK_PLANK_VERTICAL_SLAB = block("vertical_dark_oak_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.DARK_OAK_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_JUNGLE_PLANK_VERTICAL_SLAB = block("vertical_jungle_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.JUNGLE_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_MANGROVE_PLANK_VERTICAL_SLAB = block("vertical_mangrove_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.MANGROVE_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_OAK_PLANK_VERTICAL_SLAB = block("vertical_oak_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.OAK_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_SPRUCE_PLANK_VERTICAL_SLAB = block("vertical_spruce_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.SPRUCE_PLANKS), 150);
    public static final RegistrySupplier<Block> VERTICAL_VERDANT_PLANK_VERTICAL_SLAB = block("vertical_verdant_plank_vertical_slab", () -> new VerticalSlabBlock(VERDANT_PLANKS));
    public static final RegistrySupplier<Block> VERTICAL_WARPED_PLANK_VERTICAL_SLAB = block("vertical_warped_plank_vertical_slab", () -> new VerticalSlabBlock(Blocks.WARPED_PLANKS));

    public static final RegistrySupplier<Block> ACACIA_MOSAIC_VERTICAL_SLAB = block("acacia_mosaic_vertical_slab", () -> new VerticalSlabBlock(ACACIA_MOSAIC), 150);
    public static final RegistrySupplier<Block> BAMBOO_MOSAIC_VERTICAL_SLAB = block("bamboo_mosaic_vertical_slab", () -> new VerticalSlabBlock(Blocks.BAMBOO_MOSAIC), 150);
    public static final RegistrySupplier<Block> BIRCH_MOSAIC_VERTICAL_SLAB = block("birch_mosaic_vertical_slab", () -> new VerticalSlabBlock(BIRCH_MOSAIC), 150);
    public static final RegistrySupplier<Block> CHERRY_MOSAIC_VERTICAL_SLAB = block("cherry_mosaic_vertical_slab", () -> new VerticalSlabBlock(CHERRY_MOSAIC), 150);
    public static final RegistrySupplier<Block> CRIMSON_MOSAIC_VERTICAL_SLAB = block("crimson_mosaic_vertical_slab", () -> new VerticalSlabBlock(CRIMSON_MOSAIC));
    public static final RegistrySupplier<Block> DARK_OAK_MOSAIC_VERTICAL_SLAB = block("dark_oak_mosaic_vertical_slab", () -> new VerticalSlabBlock(DARK_OAK_MOSAIC), 150);
    public static final RegistrySupplier<Block> JUNGLE_MOSAIC_VERTICAL_SLAB = block("jungle_mosaic_vertical_slab", () -> new VerticalSlabBlock(JUNGLE_MOSAIC), 150);
    public static final RegistrySupplier<Block> MANGROVE_MOSAIC_VERTICAL_SLAB = block("mangrove_mosaic_vertical_slab", () -> new VerticalSlabBlock(MANGROVE_MOSAIC), 150);
    public static final RegistrySupplier<Block> OAK_MOSAIC_VERTICAL_SLAB = block("oak_mosaic_vertical_slab", () -> new VerticalSlabBlock(OAK_MOSAIC), 150);
    public static final RegistrySupplier<Block> SPRUCE_MOSAIC_VERTICAL_SLAB = block("spruce_mosaic_vertical_slab", () -> new VerticalSlabBlock(SPRUCE_MOSAIC), 150);
    public static final RegistrySupplier<Block> VERDANT_MOSAIC_VERTICAL_SLAB = block("verdant_mosaic_vertical_slab", () -> new VerticalSlabBlock(VERDANT_MOSAIC));
    public static final RegistrySupplier<Block> WARPED_MOSAIC_VERTICAL_SLAB = block("warped_mosaic_vertical_slab", () -> new VerticalSlabBlock(WARPED_MOSAIC));

    public static final RegistrySupplier<Block> CUT_COPPER_VERTICAL_SLAB = block("cut_copper_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.UNAFFECTED, Blocks.CUT_COPPER));
    public static final RegistrySupplier<Block> EXPOSED_CUT_COPPER_VERTICAL_SLAB = block("exposed_cut_copper_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.EXPOSED, Blocks.EXPOSED_CUT_COPPER));
    public static final RegistrySupplier<Block> WEATHERED_CUT_COPPER_VERTICAL_SLAB = block("weathered_cut_copper_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.WEATHERED, Blocks.WEATHERED_CUT_COPPER));
    public static final RegistrySupplier<Block> OXIDIZED_CUT_COPPER_VERTICAL_SLAB = block("oxidized_cut_copper_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.OXIDIZED, Blocks.OXIDIZED_CUT_COPPER));
    public static final RegistrySupplier<Block> WAXED_CUT_COPPER_VERTICAL_SLAB = block("waxed_cut_copper_vertical_slab", () -> new VerticalSlabBlock(Blocks.WAXED_CUT_COPPER));
    public static final RegistrySupplier<Block> WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB = block("waxed_exposed_cut_copper_vertical_slab", () -> new VerticalSlabBlock(Blocks.WAXED_EXPOSED_CUT_COPPER));
    public static final RegistrySupplier<Block> WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB = block("waxed_weathered_cut_copper_vertical_slab", () -> new VerticalSlabBlock(Blocks.WAXED_WEATHERED_COPPER));
    public static final RegistrySupplier<Block> WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB = block("waxed_oxidized_cut_copper_vertical_slab", () -> new VerticalSlabBlock(Blocks.WAXED_OXIDIZED_CUT_COPPER));

    public static final RegistrySupplier<Block> SCULKED_DEEPSLATE_BRICKS = block("sculked_deepslate_bricks", () -> new BuildingBlock(Blocks.DEEPSLATE_BRICKS));
    public static final RegistrySupplier<Block> SCULKED_DEEPSLATE_BRICK_SLAB = block("sculked_deepslate_brick_slab", () -> new SlabsBlock(Blocks.DEEPSLATE_BRICKS));
    public static final RegistrySupplier<Block> SCULKED_DEEPSLATE_BRICK_STAIRS = block("sculked_deepslate_brick_stairs", () -> new StairsBlock(Blocks.DEEPSLATE_BRICKS));
    public static final RegistrySupplier<Block> SCULKED_DEEPSLATE_BRICK_WALL = block("sculked_deepslate_brick_wall", () -> new WallsBlock(Blocks.DEEPSLATE_BRICKS));
    public static final RegistrySupplier<Block> SCULKED_DEEPSLATE_BRICK_VERTICAL_SLAB = block("sculked_deepslate_brick_vertical_slab", () -> new VerticalSlabBlock(Blocks.DEEPSLATE_BRICKS));
    public static final RegistrySupplier<Block> SCULKED_DEEPSLATE_TILES = block("sculked_deepslate_tiles", () -> new BuildingBlock(Blocks.DEEPSLATE_TILES));
    public static final RegistrySupplier<Block> SCULKED_DEEPSLATE_TILE_SLAB = block("sculked_deepslate_tile_slab", () -> new SlabsBlock(Blocks.DEEPSLATE_TILES));
    public static final RegistrySupplier<Block> SCULKED_DEEPSLATE_TILE_STAIRS = block("sculked_deepslate_tile_stairs", () -> new StairsBlock(Blocks.DEEPSLATE_TILES));
    public static final RegistrySupplier<Block> SCULKED_DEEPSLATE_TILE_WALL = block("sculked_deepslate_tile_wall", () -> new WallsBlock(Blocks.DEEPSLATE_TILES));
    public static final RegistrySupplier<Block> SCULKED_DEEPSLATE_TILE_VERTICAL_SLAB = block("sculked_deepslate_tile_vertical_slab", () -> new VerticalSlabBlock(Blocks.DEEPSLATE_TILES));

    public static final RegistrySupplier<Block> ACACIA_LADDER = block("acacia_ladder", LaddersBlock::new);
    public static final RegistrySupplier<Block> BAMBOO_LADDER = block("bamboo_ladder", LaddersBlock::new);
    public static final RegistrySupplier<Block> BIRCH_LADDER = block("birch_ladder", LaddersBlock::new);
    public static final RegistrySupplier<Block> CHERRY_LADDER = block("cherry_ladder", LaddersBlock::new);
    public static final RegistrySupplier<Block> CRIMSON_LADDER = block("crimson_ladder", LaddersBlock::new);
    public static final RegistrySupplier<Block> DARK_OAK_LADDER = block("dark_oak_ladder", LaddersBlock::new);

    private static RegistrySupplier<Block> block(String id, Supplier<Block> blockSupplier) {
        RegistrySupplier<Block> block = BLOCKS.register(id, blockSupplier);
        BignayItems.ITEMS.register(id, () -> new ItemForBlock(block::get));
        return block;
    }

    private static RegistrySupplier<Block> blockOnly(String id, Supplier<Block> blockSupplier) {
        return BLOCKS.register(id, blockSupplier);
    }

    private static RegistrySupplier<Block> block(String id, Supplier<Block> blockSupplier, int burnTime) {
        RegistrySupplier<Block> block = BLOCKS.register(id, blockSupplier);
        BignayItems.ITEMS.register(id, () -> new BurnableBlockItem(block.get(), new Item.Properties(), burnTime));
        return block;
    }

    private static RegistrySupplier<Block> equipablePumpkin(String id, Supplier<Block> blockSupplier) {
        RegistrySupplier<Block> block = BLOCKS.register(id, blockSupplier);
        BignayItems.ITEMS.register(id, () -> new EquipablePumpkinItem(block));
        return block;
    }
}
